### ISSUE TITLE
setVideoQuality() does nothing (-qscale is ignored)

### ISSUE THREAD

**Issue by moneytoo** [bramp/ffmpeg-cli-wrapper#101]
I use ffmpeg version 3.2.4 (static build on Windows) to convert videos using ``libx264``. Conversion always finishes successfully but setting the quality via ``setVideoQuality()`` has no effect (output file size is always the same with no difference in picture). 
When I ran ffmpeg with the same args as used by the wrapper, I noticed following message
```
[libx264 @ 0000000000e45c80] -qscale is ignored, -crf is recommended.
```
Using ``addExtraArgs("-crf", "25")`` works.

**Comment by bramp** [comment]
Thanks for your feedback.

"-qscale is ignored, -crf is recommended" comes from the libx264 codec, and that's not something I can detect ahead of time would be a problem. I have made the choice that this project wouldn't try and learn all the edge cases with each codec, as that would make it harder to use programatically.

However, I think it is worth adding a new setConstantRateFactor(..) method.

**Comment by moneytoo** [comment]
Thanks for your prompt reaction. I was thinking it's something like that. The libx264 message is logged as warning in ffmpeg output. Is there place where such messages are collected? I didn't look that deep in the wrapper so I'm not sure if executing ffmpeg manually with the same parameters is the only way finding similar cases.

**Comment by bramp** [comment]
Yes, currently I don't collect the warnings or errors. That was on my eventual TODO list.
