### ISSUE TITLE
setStrict() does not exist, addExtraArgs("-strict", "experiemental") throws Exception

### ISSUE THREAD

**Issue by idoor88** [bramp/ffmpeg-cli-wrapper#103]
Hi all,

I am trying to run this command line from the wrapper:
ffmpeg -i input.mp4 -i input.wav -c:v copy -c:a aac -strict experimental output.mp4
with this code:

FFmpegBuilder builder = new FFmpegBuilder()
				.setInput("input.mp4")  
			    .setInput("input.wav")  
			    .addExtraArgs("-c:v copy -c:a aac")
			   .addExtraArgs("-strict", "experimental")
			    .addOutput("output.mp4")
			    .done();
I got exception: Unable to find a suitable output format for 'experimental'
also the logging shows this command line is generated:
ffmpeg -y -v error -c:v copy -c:a aac -strict experimental -i input.wav output.mp4
no input.mp4 is fed in from this command line and order also changed
Any idea?
Thanks

**Comment by bramp** [comment]
[setStrict](https://bramp.github.io/ffmpeg-cli-wrapper/net/bramp/ffmpeg/builder/FFmpegOutputBuilder.html#setStrict-net.bramp.ffmpeg.builder.FFmpegBuilder.Strict-)() is on the FFmpegOutputBuilder, as it changes the encoding codec's behaviour.

I wanted to add a FFmpegInputBuilder, and when/if I do that, it should also belong there.
