### ISSUE TITLE
Images to video

### ISSUE THREAD

**Issue by christiedavel** [bramp/ffmpeg-cli-wrapper#105]
How do I add multiple images as input in order to create a video.  I would imagine one should be able to do something like this:

FFmpegBuilder builder = new FFmpegBuilder()
.addInput("/Users/christie/java/ffmpeg/image003.png")
.addInput("/Users/christie/java/ffmpeg/image001.png")
.addInput("/Users/christie/java/ffmpeg/image002.png")

**Comment by bramp** [comment]
https://trac.ffmpeg.org/wiki/Slideshow explains how to use FFmpeg to create a video from images. Sadly it doesn't support adding lots of indiviual images, but it does support the `-i img%03d.png`

So you can do the following:
```java
FFmpegBuilder builder = new FFmpegBuilder()
    .addInput("/Users/christie/java/ffmpeg/image%03d.png")
    .addOutput("output.mp4")
    .setVideoFrameRate(FFmpeg.FPS_24)
    .done();
```

I've added an example here: https://github.com/bramp/ffmpeg-cli-wrapper/wiki/Random-Examples

**Comment by christiedavel** [comment]
Thank you for the reply Andrew.
