### ISSUE TITLE
The ffmpeg program is only provided for script compatibility

### ISSUE THREAD

**Issue by leccyril** [bramp/ffmpeg-cli-wrapper#106]
We have this message in debian or ubuntu installation, do you will switch with the new library ? 

_The ffmpeg program is only provided for script compatibility and will be removed
in a future release. It has been deprecated in the Libav project to allow for
incompatible command line syntax improvements in its replacement called avconv
(see Changelog for details). Please use avconv instead.
Hyper fast Audio and Video encoder_

**Comment by isanvicente** [comment]
Readme says: "We only the support the original FFmpeg, not the libav version"

https://github.com/bramp/ffmpeg-cli-wrapper#install-ffmpeg-on-ubuntu

From your message seems you are using the libav version...

**Comment by bramp** [comment]
Yes, only ffmpeg is supported.

#126 tracks the support of avconv, but don't expect it any time soon, unless someone volunteers.
