### ISSUE TITLE
create thumbnail from video

### ISSUE THREAD

**Issue by leccyril** [bramp/ffmpeg-cli-wrapper#107]
It is possible with java code to createimage from video with the java code? 

ffmpeg -i $uploaded_file -ss 00:00:01.000 -vframes 1 output.png

**Comment by bramp** [comment]
Yup, take a look at once of our examples: https://github.com/bramp/ffmpeg-cli-wrapper/wiki/Random-Examples#example-3-take-a-thumbnail-from-a-video-and-scale-it-down

**Comment by namannigam** [comment]
@bramp Would be great to pose the link to Random Examples in the ReadMe as well.
