### ISSUE TITLE
How to deal with the Exception: Target size must be used with setInput(FFmpegProbeResult) ?

### ISSUE THREAD

**Issue by RiceOfForest** [bramp/ffmpeg-cli-wrapper#109]
I failed to run the demo (video encoding)  in my mac (jdk1.8 & osx 10.11.6)，here is the exception
```
Exception in thread "main" java.lang.IllegalStateException: Target size must be used with setInput(FFmpegProbeResult)
	at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at net.bramp.ffmpeg.builder.FFmpegOutputBuilder.build(FFmpegOutputBuilder.java:640)
	at net.bramp.ffmpeg.builder.FFmpegBuilder.build(FFmpegBuilder.java:278)
	at net.bramp.ffmpeg.job.SinglePassFFmpegJob.<init>(SinglePassFFmpegJob.java:28)
	at net.bramp.ffmpeg.job.SinglePassFFmpegJob.<init>(SinglePassFFmpegJob.java:17)
	at net.bramp.ffmpeg.FFmpegExecutor.createJob(FFmpegExecutor.java:32)
	at com.transcoding.App.main(App.java:53)
```
and my code is given by
      
       
        FFmpeg ffmpeg = new FFmpeg("/path/to/ffmpeg");
        FFprobe ffprobe = new FFprobe("/path/to/ffprobe");

        FFmpegBuilder builder = new FFmpegBuilder()

            .setInput("1.avi")     // Filename, or a FFmpegProbeResult
            .overrideOutputFiles(true) // Override the output if it exists

            .addOutput("2.mp4")   // Filename for the destination
            .setFormat("mp4")        // Format is inferred from filename, or can be set
            .setTargetSize(250000)  // Aim for a 250KB file 250_000

            .disableSubtitle()       // No subtiles

            .setAudioChannels(1)         // Mono audio
            .setAudioCodec("aac")        // using the aac codec
            .setAudioSampleRate(48000)  // at 48KHz 48_000
            .setAudioBitRate(32768)      // at 32 kbit/s

            .setVideoCodec("libx264")     // Video using x264
            .setVideoFrameRate(24, 1)     // at 24 frames per second
            .setVideoResolution(640, 480) // at 640x480 resolution

            .setStrict(FFmpegBuilder.Strict.EXPERIMENTAL) // Allow FFmpeg to use experimental specs
            .done();

        FFmpegExecutor executor = new FFmpegExecutor(ffmpeg, ffprobe);

        // Run a one-pass encode
        executor.createJob(builder).run();

        // Or run a two-pass encode (which is slower at the cost of better quality)
        executor.createTwoPassJob(builder).run();

How to deal with this exception？

**Comment by RiceOfForest** [comment]
I'm so fool...... delete the following code
`.setTargetSize(250_000)`
and the weather cleaned up

**Comment by bramp** [comment]
Or call setInput which takes a FFmpegProbeResult, instead of a file name.

SetTargetSize needs information about the media, to calculate the nitrate, etc that is not available unless you probe the input media.

Feel free to suggest a better error message.
