### ISSUE TITLE
SetWorkingDirectory

### ISSUE THREAD

**Issue by nvkaymanov** [bramp/ffmpeg-cli-wrapper#110]
Hi! 
In EXAMPLE 5 you show the installation working directory. But I can't do the same.. in the class RunProcessFunction missing setWorkingDirectory method. How can I set the working directory?

**Comment by bramp** [comment]
RunProcessFunction does indeed have a setWorkingDirectory method: https://github.com/bramp/ffmpeg-cli-wrapper/blob/master/src/main/java/net/bramp/ffmpeg/RunProcessFunction.java#L43

What version of the library are you using? Perhaps you can share your code and I'll spot the issue.

**Comment by nvkaymanov** [comment]
Hmm, interesting. I see this method you have in a thread on Gita.. I use the version <version>0.6.1</version> and I don't have this method
