### ISSUE TITLE
-filter_complex

### ISSUE THREAD

**Issue by nvkaymanov** [bramp/ffmpeg-cli-wrapper#111]
In my project I use the following ffmpeg command, that successfully works:
ffmpeg -y -i input1.mp4 -i input2.mp4 -loop 1 -framerate 25 -t 5 -i picture.png -i input3.mp4 -i input4.mp4 -f lavfi -t 1 -i anullsrc -filter_complex \"[0:v][0:a][1:v][1:a][2][5][3:v][3:a][4:v][4:a]concat=n=5:v=1:a=1\" -vcodec libx264 -movflags faststart -g 25 -sc_threshold 0 -refs 5 -ar 22500 -ac 2 -ab 128k -pix_fmt yuv420p -threads 0 -r 25 -aspect 704:400 -b:v 1100k final.mp4
This command concat 4 videos and picture. 
In the end we have the first video, then second video, then the picture is converted into a video with a duration of 5 seconds, then the third video, and then the fourth video
How can I describe it using your library?

**Comment by coarsehorse** [comment]
I'm also looking for a way to pass `loop 1`

**Comment by Euklios** [comment]
This should be possible with #339
