### ISSUE TITLE
Unable to merge image and audio (mp3) input to an video output (mp4)

### ISSUE THREAD

**Issue by yogesh-golande** [bramp/ffmpeg-cli-wrapper#112]
I want to combine an image and an audio file to create a video output.
I'm able to do it from command line:
ffmpeg -loop 1 -i /tmp/image.jpeg -i /tmp/audiot.mp3 -vf 'scale=320:trunc(ow/a/2)*2' -acodec  libvo_aacenc -b:a 192k -shortest /tmp/output.mp4

But when  I'm trying to implement the same behavior using ffmpeg-cli-wrapper java, the program just keeps running indefinitely.

If I try the same program without setting -loop 1, then it executes successfully but only converts audio to video and ignores the image.

I couldn't find any example for this online. If someone knows how to implement this behavior, please let me know.
I have attached my sample test java program.
[Test.txt](https://github.com/bramp/ffmpeg-cli-wrapper/files/1159483/Test.txt)

**Comment by bramp** [comment]
I ran your sample program, and it does indeed run indefinitely, however, when it does the same if ran directly from the command line. So this is not a limitation of this library, but a misuse of ffmpeg.

However, you have two options to fix this. Either:

1) Set a duration, "-t 30", and the video will end up being 30 seconds long
```java
FFmpegBuilder builder = new FFmpegBuilder()
    ...
    .addOutput(Samples.output_mp4)
    .setDuration(30, TimeUnit.SECONDS)
    ...
```

2) Or add the "-shortest" flag, in which case the video will be the length of the shortest input, which should be the length of your audio track.
```java
FFmpegBuilder builder = new FFmpegBuilder()
    ...
    .addOutput(Samples.output_mp4)
    .addExtraArgs("-shortest")
    ...
```
