### ISSUE TITLE
[NULL @ 05277180] Unable to find a suitable output format for 'NUL'

### ISSUE THREAD

**Issue by valnaumov** [bramp/ffmpeg-cli-wrapper#113]
I want to extract and trim an audio from the video. Here's what I do:

	FFmpeg ffmpeg = new FFmpeg('d:\\Valya\\projects\\audio-trimmer\\ffmpeg\\bin\\ffmpeg.exe')
	FFprobe ffprobe = new FFprobe("d:\\Valya\\projects\\audio-trimmer\\ffmpeg\\bin\\ffprobe.exe");

	FFmpegBuilder builder = new FFmpegBuilder()
	.setInput("d:\\Valya\\projects\\audio-trimmer
\\VODChapter_20090309_22320100_22382200_NL.mp4")    
       .setPass(1)
	.addOutput("d:\\Valya\\projects\\audio-trimmer\\output.wav")   // Filename for the destination
	.setStartOffset(24, TimeUnit.SECONDS)
	.setDuration(155, TimeUnit.SECONDS)
	.done();

	FFmpegExecutor executor = new FFmpegExecutor(ffmpeg, ffprobe);

	// Run a one-pass encode
	executor.createJob(builder).run();

I'm using the version 0.5 and ffmpeg of version 3.3.2.

Why is 'NUL' passed among other arguments to ffmpeg?

Can I disable log file creation, i.e. `76ac847a-e9d8-49bb-8918-7bb24a541614-0.log`, `76ac847a-e9d8-49bb-8918-7bb24a541614-0.log.mbtree`?

EDIT:
Sorry, it was my fault. Shouldn't be setting pass `.setPass(1)`. At first I've also tried to run in two passes, which is a mistake as well in this case.

The issue can be closed

**Comment by bramp** [comment]
Hey valnaumov, sounds like you fixed the issue yourself so I'll close this, but just to clarify what is happening.

With two pass encoding, ffmpeg has to process the video twice. The first pass ffmpeg record various statistics about each frame. These are store in the .log and .mbtree files. Then the second pass, ffmpeg uses these logs, so it can do a better job of compressing the video.

On the first pass, we have to set the output to /dev/null (on Linux), or NUL (on Windows). This is a special file, that doesn't actually get written to disk. However, it looks like ffmpeg is getting tripped up on what format to write that file out as. To work around that, you would need to setFormat("mp4"), and two pass will work.
