### ISSUE TITLE
ProgressListener nerver trigered but the video is in converting

### ISSUE THREAD

**Issue by PHClement** [bramp/ffmpeg-cli-wrapper#115]
Hello,

I'm working on a project with your library and I need the progress listener but this is never called during a conversion, can you help me ?

    		FFmpeg ffmpeg = new FFmpeg(Config.FFMPEG_PATH);
			FFprobe ffprobe = new FFprobe(Config.FFMPEG_FFPROBE);
			FFmpegProbeResult in = ffprobe.probe(file.getAbsolutePath());

			int idx = file.getName().lastIndexOf('.');

			FFmpegBuilder builder = new    FFmpegBuilder().setInput(file.getAbsolutePath()).overrideOutputFiles(true).addOutput(file.getParentFile().getAbsolutePath() + File.separator + file.getName().substring(0, idx) + ".mp4").setFormat("mp4").done();

			FFmpegExecutor executor = new FFmpegExecutor(ffmpeg, ffprobe);

			System.out.println("[-->] Conversion du fichier " + file.getName() + ", démarrage...");

			FFmpegJob job = executor.createJob(builder, new ProgressListener() {
				final double duration_ns = in.getFormat().duration * TimeUnit.SECONDS.toNanos(1);

				@Override
				public void progress(Progress progress) {
					double percentage = progress.out_time_ms / duration_ns;

					if(progressConverting >= 100){
						onFinish();
						System.out.println("[-->] Conversion terminé : " + file.getName());
					}
					onProgress((int) percentage);
					System.out.println(percentage + " %");
				}
			});
			job.run();

**Comment by bramp** [comment]
Sorry for being slow to take a look at this issue, but, @PHClement did you resolve your issue? If so, how?
