### ISSUE TITLE
-movflags option

### ISSUE THREAD

**Issue by nsilberman** [bramp/ffmpeg-cli-wrapper#12]
Hi
there's no implementation fo the `-movflags` option in order, for example, to move the moov atom at the beginning of the encoded file (with faststart)

**Comment by nsilberman** [comment]
and the same for  -copyinkf :) any possiblitiy to add "custom" parameters ?

**Comment by bramp** [comment]
You are correct those flags don't exist. Patches are welcome on all
suggestions, otherwise I can try and get to them at a later date.

**Comment by nsilberman** [comment]
https://github.com/bramp/ffmpeg-cli-wrapper/pull/14
hope it's ok, I'm not the best java dev :)

**Comment by bramp** [comment]
Fixed by your pull request. Thanks.

**Comment by VAle512** [comment]
Hi, the -movflags is no longer present in the current build. Is there a reason why it was removed?
