### ISSUE TITLE
Cannot find net.bramp.ffmpeg.lang.NewProcessAnswer

### ISSUE THREAD

**Issue by pudility** [bramp/ffmpeg-cli-wrapper#120]
I cannot find where net.bramp.ffmpeg.lang is. I am trying to follow the example, but I cannot find `net.bramp.ffmpeg.lang.NewProcessAnswer`.

**Comment by bramp** [comment]
It is found here: https://github.com/bramp/ffmpeg-cli-wrapper/blob/master/src/test/java/net/bramp/ffmpeg/lang/NewProcessAnswer.java

But is only available in tests, as it is used to mock a result, to make the test quick and repeatable.

You can find good examples in the readme: https://github.com/bramp/ffmpeg-cli-wrapper/blob/master/README.md

**Comment by pudility** [comment]
Thank you for the help :)
