### ISSUE TITLE
How can i Pad Video using this wrapper. 

### ISSUE THREAD

**Issue by MachineIntelligence6** [bramp/ffmpeg-cli-wrapper#121]
Hi 

How can i Pad Video using this wrapper. 
the ffmpeg command is:

`ffmpeg -i <input-file> -filter:v "pad=width=<width>:height=<height>:x=<x>:y=<y>" <output-file>`

Thanks

**Comment by bramp** [comment]
We don't have a -filter:v flag support right now. We do have [setComplexVideoFilter()](https://bramp.github.io/ffmpeg-cli-wrapper/net/bramp/ffmpeg/builder/FFmpegOutputBuilder.html#setComplexVideoFilter-java.lang.String-), which would most likely do what you want.

However, you could also use `addExtraArgs("-filter:v", "pad=width=<width>:height=<height>:x=<x>:y=<y>")`.

**Comment by Euklios** [comment]
In addition to `addExtraArgs`, `setVideoFilter` has been introduced at some point
I'll close this, as the question seems to be answered.
Feel free to re-open if this is not the case.
