### ISSUE TITLE
Unable to set duration when generating video from images

### ISSUE THREAD

**Issue by kresic-ivan-nsoft** [bramp/ffmpeg-cli-wrapper#122]
Hi, I'm trying to generate a video from images, while each image is supposed to have a different duration. However, when I use the duration, it has no effect - the generated videos are 0s long.

The code I'm using (Kotlin) is:

val builder = FFmpegBuilder()
                .addInput(uploadsDir + "image-%03d.png")
                .addExtraArgs("-t", "15")
                .addOutput(uploadsDir + "output.mp4")
                .setFormat("mp4")
                .setVideoCodec("libx264")
                .setVideoFrameRate(60.00)
                .setVideoResolution(1920, 1080)
                .done()

The logged path builder shows that a correct -t 15 flag was added. 

Any help here?

**Comment by bramp** [comment]
Do you have a equivalent ffmpeg command line that works? Quickly looking at their [wiki](https://trac.ffmpeg.org/wiki/Slideshow) it doesn't use the -t instead it sets the frame rate.

**Comment by kresic-ivan-nsoft** [comment]
There is an example here https://trac.ffmpeg.org/wiki/Slideshow#Singleimage. However, it seems as though it doesn't work without the loop flag.

Thanks for your help!
