### ISSUE TITLE
Speeding up

### ISSUE THREAD

**Issue by daulet140** [bramp/ffmpeg-cli-wrapper#127]
Hello
How can I speed up the video

**Comment by bramp** [comment]
The [ffmpeg trac](https://trac.ffmpeg.org/wiki/How%20to%20speed%20up%20/%20slow%20down%20a%20video) has some examples on speeding up a video. You'll need to figure out how to use the Java API to use what is shown there.  Our [random examples](https://github.com/bramp/ffmpeg-cli-wrapper/wiki/Random-Examples) might give you some tips.

**Comment by daulet140** [comment]
Thank you.
