### ISSUE TITLE
Divide(split) video to parts 

### ISSUE THREAD

**Issue by daulet140** [bramp/ffmpeg-cli-wrapper#128]
how i can divide video to parts, like that each parts should be 15 minute?
this code divide but  not all part for 15 minute. My video duration  is 40 minute,
and code divide to parts: 15, 18,8  minutes 

```java
FFmpegBuilder builder = new FFmpegBuilder()
     .setInput(file.getAbsolutePath()) 
     .overrideOutputFiles(true) 
     .addOutput(file.getName() + "%03d.mp4") 
     .setFormat("mp4") 
     .setAudioChannels(1)
     .setAudioCodec("aac") 
     .setAudioSampleRate(48_000) 
     .setAudioBitRate(32768) 
     .setVideoFrameRate(24, 1)
     .addExtraArgs("-map", "0")
     .addExtraArgs("-f", "segment")
     .addExtraArgs("-segment_time", "15")
     .addExtraArgs("-reset_timestamps", "1")
     .setDuration(15, TimeUnit.MINUTES)
     .setStrict(FFmpegBuilder.Strict.EXPERIMENTAL) 
     .done();
```

PS: Sorry for my English

**Comment by bramp** [comment]
Do you have an example of how to do this with the plain ffmpeg command line? If so I can tell you how to use the java API to do it.

**Comment by loversandcode** [comment]
hello, @bramp this question means something like this I guess (for simple usage)

`ffmpeg -i test.mp4 -f segment -segment_time 3 -c copy out%03d.mp4`
