### ISSUE TITLE
I want to build it to a JAR executable. But it won't build via Maven. I tried "mvn" in the directory of this project, and here's the output I got.

### ISSUE THREAD

**Issue by Ahsan-Anjum-Butt** [bramp/ffmpeg-cli-wrapper#131]
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[WARNING] The project net.bramp.ffmpeg:ffmpeg:jar:0.6.2-SNAPSHOT uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building FFmpeg Wrapper 0.6.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce) @ ffmpeg ---
[INFO]
[INFO] --- fmt-maven-plugin:1.5.0:format (default) @ ffmpeg ---
[info] Processed 95 files (0 reformatted).
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ ffmpeg ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\ahsan\Downloads\ffmpeg-cli-wrapper-master\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ ffmpeg ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ ffmpeg ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 17 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ ffmpeg ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ ffmpeg ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running net.bramp.commons.lang3.math.gson.FractionAdapterTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.231 sec - in net.bramp.commons.lang3.math.gson.FractionAdapterTest
Running net.bramp.ffmpeg.builder.FFmpegBuilderTest
Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.316 sec - in net.bramp.ffmpeg.builder.FFmpegBuilderTest
Running net.bramp.ffmpeg.builder.FormatDecimalIntegerTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.02 sec - in net.bramp.ffmpeg.builder.FormatDecimalIntegerTest
Running net.bramp.ffmpeg.builder.MetadataSpecTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in net.bramp.ffmpeg.builder.MetadataSpecTest
Running net.bramp.ffmpeg.builder.StreamSpecTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in net.bramp.ffmpeg.builder.StreamSpecTest
Running net.bramp.ffmpeg.ExamplesTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.571 sec - in net.bramp.ffmpeg.ExamplesTest
Running net.bramp.ffmpeg.FFmpegAvTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in net.bramp.ffmpeg.FFmpegAvTest
Running net.bramp.ffmpeg.FFmpegExecutorTest
Oct 07, 2017 2:06:39 PM org.glassfish.grizzly.http.server.NetworkListener start
INFO: Started listener bound to [127.0.0.1:29483]
Oct 07, 2017 2:06:39 PM org.glassfish.grizzly.http.server.HttpServer start
INFO: [HttpServer] Started.
14:06:39.340 [main] INFO net.bramp.ffmpeg.FFmpegExecutorTest - Started server at http://127.0.0.1:29483/
14:06:39.348 [main] INFO net.bramp.ffmpeg.RunProcessFunction - ffmpeg -version
14:06:39.358 [main] INFO net.bramp.ffmpeg.RunProcessFunction - ffmpeg -version
14:06:39.361 [main] INFO net.bramp.ffmpeg.RunProcessFunction - ffmpeg -version
14:06:39.364 [main] INFO net.bramp.ffmpeg.RunProcessFunction - ffmpeg -version
14:06:39.367 [main] INFO net.bramp.ffmpeg.RunProcessFunction - ffmpeg -version
14:06:39.370 [main] INFO net.bramp.ffmpeg.RunProcessFunction - ffmpeg -version
14:06:39.372 [main] INFO net.bramp.ffmpeg.RunProcessFunction - ffmpeg -version
Oct 07, 2017 2:06:39 PM org.glassfish.grizzly.http.server.NetworkListener shutdownNow
INFO: Stopped listener bound to [127.0.0.1:29483]
Tests run: 7, Failures: 0, Errors: 7, Skipped: 0, Time elapsed: 0.697 sec <<< FAILURE! - in net.bramp.ffmpeg.FFmpegExecutorTest
testTwoPass(net.bramp.ffmpeg.FFmpegExecutorTest)  Time elapsed: 0.005 sec  <<< ERROR!
java.io.IOException: Cannot run program "ffmpeg": CreateProcess error=2, The system cannot find the file specified
        at net.bramp.ffmpeg.FFmpegExecutorTest.<init>(FFmpegExecutorTest.java:47)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at net.bramp.ffmpeg.FFmpegExecutorTest.<init>(FFmpegExecutorTest.java:47)

testProgress(net.bramp.ffmpeg.FFmpegExecutorTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.io.IOException: Cannot run program "ffmpeg": CreateProcess error=2, The system cannot find the file specified
        at net.bramp.ffmpeg.FFmpegExecutorTest.<init>(FFmpegExecutorTest.java:47)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at net.bramp.ffmpeg.FFmpegExecutorTest.<init>(FFmpegExecutorTest.java:47)

testMetaTags(net.bramp.ffmpeg.FFmpegExecutorTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.io.IOException: Cannot run program "ffmpeg": CreateProcess error=2, The system cannot find the file specified
        at net.bramp.ffmpeg.FFmpegExecutorTest.<init>(FFmpegExecutorTest.java:47)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at net.bramp.ffmpeg.FFmpegExecutorTest.<init>(FFmpegExecutorTest.java:47)

testFilter(net.bramp.ffmpeg.FFmpegExecutorTest)  Time elapsed: 0 sec  <<< ERROR!
java.io.IOException: Cannot run program "ffmpeg": CreateProcess error=2, The system cannot find the file specified
        at net.bramp.ffmpeg.FFmpegExecutorTest.<init>(FFmpegExecutorTest.java:47)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at net.bramp.ffmpeg.FFmpegExecutorTest.<init>(FFmpegExecutorTest.java:47)

testIssue112(net.bramp.ffmpeg.FFmpegExecutorTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.io.IOException: Cannot run program "ffmpeg": CreateProcess error=2, The system cannot find the file specified
        at net.bramp.ffmpeg.FFmpegExecutorTest.<init>(FFmpegExecutorTest.java:47)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at net.bramp.ffmpeg.FFmpegExecutorTest.<init>(FFmpegExecutorTest.java:47)

testNormal(net.bramp.ffmpeg.FFmpegExecutorTest)  Time elapsed: 0 sec  <<< ERROR!
java.io.IOException: Cannot run program "ffmpeg": CreateProcess error=2, The system cannot find the file specified
        at net.bramp.ffmpeg.FFmpegExecutorTest.<init>(FFmpegExecutorTest.java:47)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at net.bramp.ffmpeg.FFmpegExecutorTest.<init>(FFmpegExecutorTest.java:47)

testStdout(net.bramp.ffmpeg.FFmpegExecutorTest)  Time elapsed: 0 sec  <<< ERROR!
java.io.IOException: Cannot run program "ffmpeg": CreateProcess error=2, The system cannot find the file specified
        at net.bramp.ffmpeg.FFmpegExecutorTest.<init>(FFmpegExecutorTest.java:47)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at net.bramp.ffmpeg.FFmpegExecutorTest.<init>(FFmpegExecutorTest.java:47)

Running net.bramp.ffmpeg.FFmpegTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.076 sec - in net.bramp.ffmpeg.FFmpegTest
Running net.bramp.ffmpeg.FFmpegUtilsTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in net.bramp.ffmpeg.FFmpegUtilsTest
Running net.bramp.ffmpeg.FFprobeAvTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in net.bramp.ffmpeg.FFprobeAvTest
Running net.bramp.ffmpeg.FFprobeTest
14:06:39.567 [main] DEBUG net.bramp.ffmpeg.FFprobe - {
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "Main",
            "codec_type": "video",
            "codec_time_base": "1/50",
            "codec_tag_string": "avc1",
            "codec_tag": "0x31637661",
            "width": 1280,
            "height": 720,
            "coded_width": 1280,
            "coded_height": 720,
            "has_b_frames": 0,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "16:9",
            "pix_fmt": "yuv420p",
            "level": 31,
            "chroma_location": "left",
            "refs": 1,
            "is_avc": "1",
            "nal_length_size": "4",
            "r_frame_rate": "25/1",
            "avg_frame_rate": "25/1",
            "time_base": "1/12800",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 67584,
            "duration": "5.280000",

14:06:39.624 [main] DEBUG net.bramp.ffmpeg.FFprobe -   "bit_rate": "1205959",
            "bits_per_raw_sample": "8",
            "nb_frames": "132",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0
            },
            "tags": {
                "creation_time": "1970-01-01 00:00:00",
                "language": "und",
                "handler_name": "VideoHandler"
            }
        },
        {
            "index": 1,
            "codec_name": "aac",
            "codec_long_name": "AAC (Advanced Audio Coding)",
            "profile": "LC",
            "codec_type": "audio",
            "codec_time_base": "1/48000",
            "codec_tag_string": "mp4a",
            "codec_tag": "0x6134706d",
            "sample_fmt": "fltp"
14:06:39.641 [main] DEBUG net.bramp.ffmpeg.FFprobe - ,
            "sample_rate": "48000",
            "channels": 6,
            "channel_layout": "5.1",
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/48000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 254976,
            "duration": "5.312000",
            "bit_rate": "384828",
            "max_bit_rate": "400392",
            "nb_frames": "249",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0
            },
            "tags": {
                "creation_time": "1970-01-01 00:00:00",
                "language": "und",
                "handler_name"
14:06:39.643 [main] DEBUG net.bramp.ffmpeg.FFprobe - : "SoundHandler"
            }
        }
    ],
    "format": {
        "filename": "src/test/resources/net/bramp/ffmpeg/samples/big_buck_bunny_720p_1mb.mp4",
        "nb_streams": 2,
        "nb_programs": 0,
        "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
        "format_long_name": "QuickTime / MOV",
        "start_time": "0.000000",
        "duration": "5.312000",
        "size": "1055736",
        "bit_rate": "1589963",
        "probe_score": 100,
        "tags": {
            "major_brand": "isom",
            "minor_version": "512",
            "compatible_brands": "isomiso2avc1mp41",
            "creation_time": "1970-01-01 00:00:00",
            "encoder": "Lavf53.24.2"
        }
    }
}

14:06:39.663 [main] DEBUG net.bramp.ffmpeg.FFprobe - {
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "Main",
            "codec_type": "video",
            "codec_time_base": "1/50",
            "codec_tag_string": "[27][0][0][0]",
            "codec_tag": "0x001b",
            "width": 1920,
            "height": 1080,
            "coded_width": 1920,
            "coded_height": 1080,
            "has_b_frames": 0,
            "sample_aspect_ratio": "0:1",
            "display_aspect_ratio": "0:1",
            "pix_fmt": "yuvj420p",
            "level": 42,
            "color_range": "pc",
            "color_space": "bt709",
            "color_transfer": "bt709",
            "color_primaries": "bt709",
            "chroma_location": "left",
            "field_order": "progressive",
            "refs": 1,
            "is_avc": "false",
            "nal_length_size": "0",
            "id": "0x1",
            "r_frame_rate": "2
14:06:39.664 [main] DEBUG net.bramp.ffmpeg.FFprobe - 5/1",
            "avg_frame_rate": "25/1",
            "time_base": "1/90000",
            "start_pts": 8570867078,
            "start_time": "95231.856422",
            "duration_ts": 31694552,
            "duration": "352.161689",
            "bits_per_raw_sample": "8",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            }
        },
        {
            "index": 1,
            "codec_name": "aac",
            "codec_long_name": "AAC (Advanced Audio Coding)",
            "profile": "LC",
            "codec_type": "audio",
            "codec_time_base": "1/44100",
            "codec_tag_string": "[15][0][0][0]",
            "codec_ta
14:06:39.666 [main] DEBUG net.bramp.ffmpeg.FFprobe - g": "0x000f",
            "sample_fmt": "fltp",
            "sample_rate": "44100",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "id": "0x2",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/90000",
            "start_pts": 8570867697,
            "start_time": "95231.863300",
            "duration_ts": 31695687,
            "duration": "352.174300",
            "bit_rate": "98191",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            }
        }
    ],
    "format": {
        "filename": "TS Test record.ts",
        "nb
14:06:39.668 [main] DEBUG net.bramp.ffmpeg.FFprobe - _streams": 2,
        "nb_programs": 1,
        "format_name": "mpegts",
        "format_long_name": "MPEG-TS (MPEG-2 Transport Stream)",
        "start_time": "95231.856422",
        "duration": "352.181178",
        "size": "179003772",
        "bit_rate": "4066174",
        "probe_score": 50
    }
}

14:06:39.676 [main] DEBUG net.bramp.ffmpeg.FFprobe - {
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "High",
            "codec_type": "video",
            "codec_time_base": "1/26",
            "codec_tag_string": "[27][0][0][0]",
            "codec_tag": "0x001b",
            "width": 1920,
            "height": 1080,
            "coded_width": 1920,
            "coded_height": 1088,
            "has_b_frames": 0,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "16:9",
            "pix_fmt": "yuv420p",
            "level": 41,
            "color_range": "tv",
            "color_space": "bt709",
            "color_transfer": "bt709",
            "color_primaries": "bt709",
            "chroma_location": "left",
            "refs": 1,
            "is_avc": "0",
            "nal_length_size": "0",
            "id": "0x100",
            "r_frame_rate": "167/12",
            "avg_frame_rate": "13/1"
14:06:39.679 [main] DEBUG net.bramp.ffmpeg.FFprobe - ,
            "time_base": "1/90000",
            "start_pts": 5477657,
            "start_time": "60.862856",
            "duration_ts": 378588,
            "duration": "4.206533",
            "bits_per_raw_sample": "8",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0
            }
        },
        {
            "index": 1,
            "codec_name": "aac",
            "codec_long_name": "AAC (Advanced Audio Coding)",
            "codec_type": "audio",
            "codec_time_base": "1/0",
            "codec_tag_string": "[15][0][0][0]",
            "codec_tag": "0x000f",
            "sample_fmt": "fltp",
            "sample_rate": "0",
            "channels": 0,
            "bits
14:06:39.682 [main] DEBUG net.bramp.ffmpeg.FFprobe - _per_sample": 0,
            "id": "0x101",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/90000",
            "start_pts": 5477657,
            "start_time": "60.862856",
            "duration_ts": 378588,
            "duration": "4.206533",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0
            }
        }
    ],
    "format": {
        "filename": "1.ts",
        "nb_streams": 2,
        "nb_programs": 1,
        "format_name": "mpegts",
        "format_long_name": "MPEG-TS (MPEG-2 Transport Stream)",
        "start_time": "60.862856",
        "duration": "4.206533",
        "size": "574528",
        "bit_rate": "1092639",
14:06:39.684 [main] DEBUG net.bramp.ffmpeg.FFprobe -
        "probe_score": 100
    }
}

14:06:39.692 [main] DEBUG net.bramp.ffmpeg.FFprobe - {
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "High",
            "codec_type": "video",
            "codec_time_base": "1/50",
            "codec_tag_string": "avc1",
            "codec_tag": "0x31637661",
            "width": 1920,
            "height": 1080,
            "coded_width": 1920,
            "coded_height": 1088,
            "has_b_frames": 1,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "16:9",
            "pix_fmt": "yuv420p",
            "level": 40,
            "color_range": "tv",
            "color_space": "bt709",
            "color_transfer": "bt709",
            "color_primaries": "bt709",
            "chroma_location": "left",
            "refs": 2,
            "is_avc": "true",
            "nal_length_size": "4",
            "r_frame_rate": "25/1",
            "avg_frame_rate": "25/1",
14:06:39.693 [main] DEBUG net.bramp.ffmpeg.FFprobe -
            "time_base": "1/25000",
            "start_pts": 1000,
            "start_time": "0.040000",
            "duration_ts": 4540000,
            "duration": "181.600000",
            "bit_rate": "17982770",
            "bits_per_raw_sample": "8",
            "nb_frames": "4540",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0
            },
            "tags": {
                "creation_time": "2015-10-03 16:35:06",
                "language": "eng",
                "handler_name": "MP4 Video Media Handler",
                "encoder": "AVC Coding"
            }
        },
        {
            "index": 1,
            "codec_name": "aac",

14:06:39.695 [main] DEBUG net.bramp.ffmpeg.FFprobe -         "codec_long_name": "AAC (Advanced Audio Coding)",
            "profile": "LC",
            "codec_type": "audio",
            "codec_time_base": "1/48000",
            "codec_tag_string": "mp4a",
            "codec_tag": "0x6134706d",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/48000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 8718336,
            "duration": "181.632000",
            "bit_rate": "388637",
            "max_bit_rate": "575625",
            "nb_frames": "8514",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced"
14:06:39.696 [main] DEBUG net.bramp.ffmpeg.FFprobe - : 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0
            },
            "tags": {
                "creation_time": "2015-10-03 16:35:06",
                "language": "eng",
                "handler_name": "MP4 Sound Media Handler"
            }
        }
    ],
    "format": {
        "filename": "c:\\Users\\Bob\\Always On My Mind [Program Only] - AdelΘn.mp4",
        "nb_streams": 2,
        "nb_programs": 0,
        "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
        "format_long_name": "QuickTime / MOV",
        "start_time": "0.000000",
        "duration": "181.632000",
        "size": "417127573",
        "bit_rate": "18372426",
        "probe_score": 100,
        "tags": {
            "major_brand": "mp42",
            "minor_version": "0",
            "compatible_brands": "isom",
            "creation_time": "2015-10-03 16:35:06"
        }
    }
}

Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.29 sec - in net.bramp.ffmpeg.FFprobeTest
Running net.bramp.ffmpeg.gson.NamedBitsetAdapterTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in net.bramp.ffmpeg.gson.NamedBitsetAdapterTest
Running net.bramp.ffmpeg.modelmapper.MapperTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec - in net.bramp.ffmpeg.modelmapper.MapperTest
Running net.bramp.ffmpeg.nut.NutReaderTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE! - in net.bramp.ffmpeg.nut.NutReaderTest
testNutReader(net.bramp.ffmpeg.nut.NutReaderTest)  Time elapsed: 0 sec  <<< ERROR!
java.io.IOException: Cannot run program "ffmpeg": CreateProcess error=2, The system cannot find the file specified
        at net.bramp.ffmpeg.nut.NutReaderTest.testNutReader(NutReaderTest.java:57)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at net.bramp.ffmpeg.nut.NutReaderTest.testNutReader(NutReaderTest.java:57)

Running net.bramp.ffmpeg.nut.RawHandlerStreamToAudioFormatTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in net.bramp.ffmpeg.nut.RawHandlerStreamToAudioFormatTest
Running net.bramp.ffmpeg.PreconditionsCheckInvalidNotEmptyTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in net.bramp.ffmpeg.PreconditionsCheckInvalidNotEmptyTest
Running net.bramp.ffmpeg.PreconditionsCheckInvalidStreamTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in net.bramp.ffmpeg.PreconditionsCheckInvalidStreamTest
Running net.bramp.ffmpeg.PreconditionsCheckValidNotEmptyTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in net.bramp.ffmpeg.PreconditionsCheckValidNotEmptyTest
Running net.bramp.ffmpeg.PreconditionsCheckValidStreamTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in net.bramp.ffmpeg.PreconditionsCheckValidStreamTest
Running net.bramp.ffmpeg.progress.StreamProgressParserTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in net.bramp.ffmpeg.progress.StreamProgressParserTest
Running net.bramp.ffmpeg.progress.TcpProgressParserTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in net.bramp.ffmpeg.progress.TcpProgressParserTest
Running net.bramp.ffmpeg.progress.UdpProgressParserTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in net.bramp.ffmpeg.progress.UdpProgressParserTest
Running net.bramp.ffmpeg.ReadmeTest
14:06:40.205 [main] INFO net.bramp.ffmpeg.RunProcessFunction - ffmpeg -version
14:06:40.211 [main] INFO net.bramp.ffmpeg.RunProcessFunction - ffmpeg -version
14:06:40.221 [main] INFO net.bramp.ffmpeg.RunProcessFunction - ffmpeg -version
14:06:40.226 [main] INFO net.bramp.ffmpeg.RunProcessFunction - ffmpeg -version
Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.004 sec <<< FAILURE! - in net.bramp.ffmpeg.ReadmeTest
testGetMediaInformation(net.bramp.ffmpeg.ReadmeTest)  Time elapsed: 0 sec  <<< ERROR!
java.io.IOException: Cannot run program "ffmpeg": CreateProcess error=2, The system cannot find the file specified
        at net.bramp.ffmpeg.ReadmeTest.<init>(ReadmeTest.java:26)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at net.bramp.ffmpeg.ReadmeTest.<init>(ReadmeTest.java:26)

testCreateFF(net.bramp.ffmpeg.ReadmeTest)  Time elapsed: 0 sec  <<< ERROR!
java.io.IOException: Cannot run program "ffmpeg": CreateProcess error=2, The system cannot find the file specified
        at net.bramp.ffmpeg.ReadmeTest.<init>(ReadmeTest.java:26)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at net.bramp.ffmpeg.ReadmeTest.<init>(ReadmeTest.java:26)

testVideoEncoding(net.bramp.ffmpeg.ReadmeTest)  Time elapsed: 0 sec  <<< ERROR!
java.io.IOException: Cannot run program "ffmpeg": CreateProcess error=2, The system cannot find the file specified
        at net.bramp.ffmpeg.ReadmeTest.<init>(ReadmeTest.java:26)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at net.bramp.ffmpeg.ReadmeTest.<init>(ReadmeTest.java:26)

testProgress(net.bramp.ffmpeg.ReadmeTest)  Time elapsed: 0 sec  <<< ERROR!
java.io.IOException: Cannot run program "ffmpeg": CreateProcess error=2, The system cannot find the file specified
        at net.bramp.ffmpeg.ReadmeTest.<init>(ReadmeTest.java:26)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at net.bramp.ffmpeg.ReadmeTest.<init>(ReadmeTest.java:26)

Results :

Tests in error:
  FFmpegExecutorTest.<init>:47 ╗ IO Cannot run program "ffmpeg": CreateProcess e...
  FFmpegExecutorTest.<init>:47 ╗ IO Cannot run program "ffmpeg": CreateProcess e...
  FFmpegExecutorTest.<init>:47 ╗ IO Cannot run program "ffmpeg": CreateProcess e...
  FFmpegExecutorTest.<init>:47 ╗ IO Cannot run program "ffmpeg": CreateProcess e...
  FFmpegExecutorTest.<init>:47 ╗ IO Cannot run program "ffmpeg": CreateProcess e...
  FFmpegExecutorTest.<init>:47 ╗ IO Cannot run program "ffmpeg": CreateProcess e...
  FFmpegExecutorTest.<init>:47 ╗ IO Cannot run program "ffmpeg": CreateProcess e...
  ReadmeTest.<init>:26 ╗ IO Cannot run program "ffmpeg": CreateProcess error=2, ...
  ReadmeTest.<init>:26 ╗ IO Cannot run program "ffmpeg": CreateProcess error=2, ...
  ReadmeTest.<init>:26 ╗ IO Cannot run program "ffmpeg": CreateProcess error=2, ...
  ReadmeTest.<init>:26 ╗ IO Cannot run program "ffmpeg": CreateProcess error=2, ...
  NutReaderTest.testNutReader:57 ╗ IO Cannot run program "ffmpeg": CreateProcess...

Tests run: 120, Failures: 0, Errors: 12, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23.931 s
[INFO] Finished at: 2017-10-07T14:06:40+05:00
[INFO] Final Memory: 18M/217M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project ffmpeg: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\ahsan\Downloads\ffmpeg-cli-wrapper-master\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by bramp** [comment]
Well the errors seem clear:
```
java.io.IOException: Cannot run program "ffmpeg": CreateProcess error=2, The system cannot find the file specified
```

If you want to run the tests, ffmpeg must be available on the path, or set the FFMPEG environment variable to point at it.

However, to include this in your jar, you should not need to download and compile the source yourself. You can use one of the many maven far jar plugins, that will take my prebuilt jar, and copy the classes into yours.

**Comment by Euklios** [comment]
I'll close this, as the question seems to be answered.
Feel free to re-open if this is not the case.
