### ISSUE TITLE
Possible to use an internal source?

### ISSUE THREAD

**Issue by jamesmmchugh** [bramp/ffmpeg-cli-wrapper#135]
Instead of setting a source of as an external file, is it possible to user an internal source of the java app, like an IO stream? i.e. If i want to generate images dynamically, and have ffmpeg encode these as video frames?

**Comment by bramp** [comment]
Sorry not yet. https://github.com/bramp/ffmpeg-cli-wrapper/issues/16 is the feature request tracking that.
