### ISSUE TITLE
AMR to MP3

### ISSUE THREAD

**Issue by wakyrei** [bramp/ffmpeg-cli-wrapper#136]
How do you use this project to transfer AMR to MP3 on windows and Linux? Can you provide several examples?

**Comment by bramp** [comment]
This java library is a simple wrapper around the ffmpeg command line.  If you can tell me how to do this with the ffmpeg command line, I can tell you how to use the java library.  Also, there are many examples of using the library on our https://github.com/bramp/ffmpeg-cli-wrapper/wiki/Random-Examples page.

**Comment by wakyrei** [comment]
@bramp  
Can you provide an simple example to transfer amr to mp3?

**Comment by bramp** [comment]
No. I can only provide you an example of using this library if you show me how to convert amr to MP3 with the ffmpeg command line.

**Comment by wakyrei** [comment]
ffmpeg -i 0929121000.amr 0929121000.mp3

This is amr to mp3 in command line。

**Comment by bramp** [comment]
oh, well that's a easy one. The example on the [README](https://github.com/bramp/ffmpeg-cli-wrapper) explain this one:

```java
FFmpeg ffmpeg = new FFmpeg("/path/to/ffmpeg");
FFprobe ffprobe = new FFprobe("/path/to/ffprobe");

FFmpegBuilder builder = new FFmpegBuilder()
  .setInput("0929121000.amr")     // Filename, or a FFmpegProbeResult
  .addOutput("0929121000.mp3")   // Filename for the destination
  .done();

FFmpegExecutor executor = new FFmpegExecutor(ffmpeg, ffprobe);

// Run a one-pass encode
executor.createJob(builder).run();
```

This will make the command line you specified.

**Comment by wakyrei** [comment]
thank you
