### ISSUE TITLE
how to build a ffprob command?

### ISSUE THREAD

**Issue by git4sun** [bramp/ffmpeg-cli-wrapper#138]
I want to use the ffprob command:
`ffprobe -show_frames -of compact=p=0 -f lavfi "movie=sample.mp4,select=gt(scene\,.4)"`
to capture the scene changes and then split videos accordingly. Can I use this wrapper to compose the command and get the output to a String? or to an output file? Thanks.

**Comment by bramp** [comment]
Currently the library doesn't support building ffprobe commands.

There is a [TODO](https://github.com/bramp/ffmpeg-cli-wrapper/blob/bdaac390352716e074b513566fca2f63661e7b5d/src/main/java/net/bramp/ffmpeg/FFprobe.java#L85) to do this. I'd welcome any patches if you wish to add this functionality.
