### ISSUE TITLE
split Stereo file into two mono files

### ISSUE THREAD

**Issue by lorie131** [bramp/ffmpeg-cli-wrapper#141]
Hi!

I am just started to using your ffmpeg wrapper and I am not sure how to go about converting a stereo wav file into two mono wav files.  

Below is an explanation on how to do it in ffmeg.  I am referring to the second example on the website below. 

https://trac.ffmpeg.org/wiki/AudioChannelManipulation

ffmpeg -i stereo.wav -map_channel 0.0.0 left.wav -map_channel 0.0.1 right.wav

The only way I can sortof get it to work is by using below command:

However, I don't want to create the file listed in addOutput() .  The real output is in newFilename1 and newFilename2.  Is there any way to do this without creating a dummy output file?

Thanks,
Lorie

```java
FFmpegBuilder builder = new FFmpegBuilder()
	.setVerbosity(Verbosity.DEBUG)
	.setInput(fullFilename)    // input Filename
	.overrideOutputFiles(true) // Override the output if it exists
	.addOutput("src/test/resources/temp.wav")   // output Filename
	.addExtraArgs("-map_channel", "0.0.0", newFilename1)   // output Filename
	.addExtraArgs("-map_channel", "0.0.1", newFilename2)   // output Filename				
	.done();
			
ffmpeg.run(builder);
```

**Comment by bramp** [comment]
I think you want:

```java
    FFmpegBuilder builder = new FFmpegBuilder()
      .setVerbosity(FFmpegBuilder.Verbosity.DEBUG)
      .setInput("input.mp3")
      .overrideOutputFiles(true) // Override the output if it exists
      .addOutput("left.mp3")
        .addExtraArgs("-map_channel", "0.0.0")
        .done()
      .addOutput("right.mp3")
        .addExtraArgs("-map_channel", "0.0.1")
        .done();
```

That outputs:
```ffmpeg -y -v debug -i input.mp3 -map_channel 0.0.0 left.mp3 -map_channel 0.0.1 right.mp3```

**Comment by bramp** [comment]
I also added this as an example to the wiki: https://github.com/bramp/ffmpeg-cli-wrapper/wiki/Random-Examples#example-8-convert-a-stereo-mp3-into-two-mono-tracks
