### ISSUE TITLE
Extract audio and video

### ISSUE THREAD

**Issue by green999** [bramp/ffmpeg-cli-wrapper#148]
How can I extract audio and video using this tool? Can you please advise?

For ex. in command line i can do this.
ffmpeg -i vid.avi -map 0:a audio.wav -map 0:v onlyvideo.avi

Thanks!
Kasi

**Comment by Euklios** [comment]
You can do this by adding two output streams.

```java
.addOutput("audio.wav").addExtraArgs("-map 0:a").done()
.addOutput("onlyvideo.avi").addExtraArgs("-map 0:v").done()
```
