### ISSUE TITLE
Embed the ffmpeg into this wrapper

### ISSUE THREAD

**Issue by yummish** [bramp/ffmpeg-cli-wrapper#149]
this is a feature request:
Is it possible to embed the ffmpeg into this wrapper so devs do not need to worry about cross platform etc... The ffmpeg config on different platform is kinda frustrating.

Thanks.

**Comment by bramp** [comment]
Good idea, but unsure how workable it is as I would need to provide packages for different OSes, and deal with new releases, etc. Also issues around what codecs are built in, as some have licences that forbid distribution.

I could perhaps bundle just the static builds available on ffmpeg.org. Or I could just update the docs to points devs to the static builds, to safe you the hassle of configuring it on different platforms.

**Comment by 1ghost1** [comment]
Yummish, just add location of your FFmpeg to Path variable or something like that. In linux, if downloaded from repos, ffmpeg is almost always in /usr/bin/

**Comment by Euklios** [comment]
Given how many ways there are to build ffmpeg, and how many platforms would need to be considered, I don't see this being possible at all.
Just what comes to mind right now:
 - win
 - linux
 - macos

Combined with x86 vs arm
Then there are the different static builds for different license requirements.
And then we would also have to consider hw accelerations.

So, my recommendation:
Either install using a package manager, download a static build, or create a small helper library that contains the executable version you use.
