### ISSUE TITLE
Change -v to be configurable

### ISSUE THREAD

**Issue by proweber1** [bramp/ffmpeg-cli-wrapper#15]
Hi! You in library in the class FFmpegBuilder, have such line:

args.add (" - v", "error");//TODO make configurable

Here take and transfer it a line, and better generally delete because in ffmpeg there is no such option! And because of this error it isn't written stry to the file because ffmpeg tries to understand that for an option such. When manually I take request which collected your class and I insert into the linux console and I clean parameter - v error, everything works.

**Comment by proweber1** [comment]
sorry, I was mistaken, - v error is, but it very strongly hinders me, you couldn't correct as soon as possible it?

**Comment by bramp** [comment]
You are welcome to send a patch to make it configurable.

**Comment by proweber1** [comment]
You are able to do it? It is very important as operability of my program depends on this library

**Comment by bramp** [comment]
This was fixed by 387c599be33b5af9d1b16f47fff5be06c2f1e4b0
