### ISSUE TITLE
Decode rtsp stream

### ISSUE THREAD

**Issue by erkan22789** [bramp/ffmpeg-cli-wrapper#152]
Hi
Is there any way to decode rtsp stream with ffmpeg-cli-wrapper? I want to get frames from rtsp stream but I  could not see any example about this.

**Comment by 1ghost1** [comment]
in setInput() provide rtsp stream.

**Comment by Euklios** [comment]
I'll close this, as the question seems to be answered.
Feel free to re-open if this is not the case.
