### ISSUE TITLE
Using ffmpeg-cli-wrapper without exe

### ISSUE THREAD

**Issue by Tatsukyo** [bramp/ffmpeg-cli-wrapper#153]
Hi, i just wanna ask if we can use ur wrapper without 
define the exe in the constructor:

I mean, 
`FFprobe ffprobe = new FFprobe("C:\\Users\\Tasku\\Desktop\\ffmpeg\\bin\\ffprobe.exe");`

is it possible to use it without the exe?

**Comment by bramp** [comment]
Sadly no. At some point you need the ffmpeg code, either a exe or some kind of dll. There are other projects that take the dll approach, but I found using the exe is easier to support and maintain.
