### ISSUE TITLE
not support this command '-itoffset'？

### ISSUE THREAD

**Issue by autismbug** [bramp/ffmpeg-cli-wrapper#155]
要指定 input 的 -itoffset 指令时，没法通过 FFmpegBuilder 来拼接，能否支持下？

**Comment by autismbug92** [comment]
Hello! Thank you for this project.It is helpful to me.
But I found that it did not support this command '-itoffset'.
I want to use it before the input command '-i'.
like:
ffmpeg -y -i testA.mp4 -itsoffset 10 -i testB.mp4  -filter_complex ... output.mp4
What should I do?

**Comment by Euklios** [comment]
I'll close this, as the question seems to be answered.
Feel free to re-open if this is not the case.
