### ISSUE TITLE
Can I get subtitles or know if some video file have subtitles??

### ISSUE THREAD

**Issue by kikeulloa** [bramp/ffmpeg-cli-wrapper#157]
First, it is very interesting and very useful all the code ..

I would like to extract the subtitles of videos using this code, or it's also useful to know if a video has subtitles or not, therefore, I would like to know if it is possible to do it with this code, if so, how would you do ???

**Comment by bramp** [comment]
This library just wraps the command line tool. So if you construct similar command line flags as [shown here](https://trac.ffmpeg.org/wiki/ExtractSubtitles), you should be able to extract the subtitles to say a temp file, then read them in/do with what you need.

**Comment by Euklios** [comment]
I'll close this, as the question seems to be answered.
Feel free to re-open if this is not the case.
