### ISSUE TITLE
Is it possible to interrupt FFMPEG?

### ISSUE THREAD

**Issue by 1ghost1** [bramp/ffmpeg-cli-wrapper#158]
Hi I need to interrupt execution on certain conditions, is it possible or do I need to do some shamaning on source code?

**Comment by hexerrus** [comment]
Pretty interested how to do this as well

**Comment by 1ghost1** [comment]
I might have found a work around for this.

On a separate thread create a while loop(with a termination variable pre-specified, like while(recording)), in that loop record small piece of video(1 second long for example) per run and give them distinct names so you can find and concat them afterwards, then after you recorded enough seconds you just concat them into one big video and delete smaller pieces.

Yes its VERY VERY fucky way to deal with things, but I really really dont wanna dig code and implement it myself.

**Comment by bramp** [comment]
If you wish to interrupt ffmpeg, you should manage the Process yourself, and use this library to build the command line arguments only. For example:

```java
    FFmpegBuilder builder = new FFmpegBuilder()
        .setInput("input")
        .addOutput("output.mp4")
        .done();

    List<String> args = new ArrayList<>();
    args.add("/path/to/ffmpeg");
    args.addAll(builder.build());

    ProcessBuilder processBuilder = new ProcessBuilder(args);
    processBuilder.redirectErrorStream(true);

    Process p = processBuilder.start();

    Thread.sleep(1000);
    
    p.destroy(); // Interrupt
```

You may wish to read stdout, and deal with other error situations.  Example of how all this is hidden from you is in [FFcommon.java](https://github.com/bramp/ffmpeg-cli-wrapper/blob/master/src/main/java/net/bramp/ffmpeg/FFcommon.java#L101).

**Comment by 1ghost1** [comment]
Oh yeeeeee thanks!
