### ISSUE TITLE
Remove @NonNull, @Nullable and @CheckReturnValue Annotations to enable backwards compatibility with Java8

### ISSUE THREAD

**Issue by Ailener** [bramp/ffmpeg-cli-wrapper#160]
****
I'm currently using Java 8, but its not backwards compatible with this library as there are type annotations that are not needed anymore and they don't exist in Java 8. Is it possible that we can remove these annotations or upgrade the library to Java 8?

Thanks

**Comment by bramp** [comment]
Travis tests this library with:
  - openjdk7
  - openjdk8
  - oraclejdk8
  - oraclejdk9

So I'm unsure this is related to you use of Java 8. Could you provide a specific error message. Thanks.

**Comment by bramp** [comment]
Closing due to lack of update. Feel free to reopen if needed.
