### ISSUE TITLE
How can I set the filter_complex  

### ISSUE THREAD

**Issue by Gillish** [bramp/ffmpeg-cli-wrapper#168]
I need to convert the below command string in to ffmpeg-cli-wrapper . I am looking for the attribute to set filter_complex value. I tried setAudioFilter but got an error.

```shell
ffmpeg -i in.wav -i insert.wav -filter_complex "[0]atrim=0:94[pre];[0]atrim=124,asetpts=PTS-STARTPTS[post];[pre][1][post]concat=n=3:v=0:a=1" out.wav
```

**Comment by bramp** [comment]
Do the examples in https://github.com/bramp/ffmpeg-cli-wrapper/wiki/Random-Examples help, specifically [Example 7](https://github.com/bramp/ffmpeg-cli-wrapper/wiki/Random-Examples#example-7-complex-filters)

**Comment by Gillish** [comment]
Thank you.
