### ISSUE TITLE
How to set or get ffmpeg path ?

### ISSUE THREAD

**Issue by mohamedmorsi95** [bramp/ffmpeg-cli-wrapper#173]
Actually I don't know the structure of this project I only want to convert songs to mp3 and reduce the bitrate. 

When I used this lib I just set 

FFmpeg ffmpeg = new FFmpeg();
FFprobe ffprobe = new FFprobe();

To set the default path which I don't know how to get or what is it ,I got error nullpointerException on 

FFmpegExecutor executor = new FFmpegExecutor(ffmpeg, ffprobe);

Which I think that mean I have a error with initializing ffmpeg and ffprobe 

So how to set or get the ffmpeg and ffprobe paths?

**Comment by Omar-Riaz** [comment]
You need to specify absolute paths to the ffmpeg and ffprobe executables, which will depend on your OS. If you want, you can place them in the working directory and refer to that in your code [System.getProperty("user.dir")]
