### ISSUE TITLE
Unable to encode VBR

### ISSUE THREAD

**Issue by st-h** [bramp/ffmpeg-cli-wrapper#176]
**Is your feature request related to a problem? Please describe.**
It is not possible to encode using vbr as described [here](https://trac.ffmpeg.org/wiki/Encode/MP3) because the `qscale` param can not be set at the correct position. I tried to use `extraArgs`, but they get set before the input is set. Encoding params however need to be set after the input.

**Describe the solution you'd like**
Adding a parameter like:
```
public FFmpegBuilder setVBR(Integer quality) 
```
which sets the `qscale` flag.

Alternatively we could use a more general `outputArgs` parameter.

**Describe alternatives you've considered**
I have first solution ready as an implementation and will be happy to submit a PR once we agreed what is the best way to add this feature.

**Comment by bramp** [comment]
I'll happily accept a `setVBR` parameter.

Also, https://github.com/bramp/ffmpeg-cli-wrapper/issues/91 (when finished) would allow better placement of the extraArgs.

**Comment by st-h** [comment]
that would be awesome :)
