### ISSUE TITLE
how to use ffmpeg-cli-wrapper to make m3u8 

### ISSUE THREAD

**Issue by lijiazhou** [bramp/ffmpeg-cli-wrapper#182]
ffmpeg -i source.mp4 -codec:v libx264 -codec:a mp3 -map 0 -f ssegment -segment_format mpegts -segment_list playlist.m3u8 -segment_time 10 out%03d.ts

how do i perform the above command using ffmpeg-cli-wrapper thx
plz be so kind sending me an email with the answer too
my email address is lijz@safeinfo.com.cn

**Comment by maziqiang12138** [comment]
老哥 你的这个问题解决了么   想请教下

**Comment by lijiazhou** [comment]
没解决 直接用命令了

**Comment by Euklios** [comment]
Generating m3u8 playlists should now be possible thanks to #322
