### ISSUE TITLE
How to Trim Audio?

### ISSUE THREAD

**Issue by JulianChow94** [bramp/ffmpeg-cli-wrapper#185]
I've been looking through the API documentation but haven't found the answer. Basically i'm looking for the functionality that lets me trim a input audio file, specify a start time and a end time and it spits out a new file that only contains the data between the 2 timestamps.

Something similar to this https://stackoverflow.com/questions/20295398/ffmpeg-clip-audio-interval-with-starting-and-end-time

Please let me know if I just missed something in the docs!

**Comment by dchen150** [comment]
how did you resolve this? @JulianChow94
