### ISSUE TITLE
Is possible run(); return a java.io.File?

### ISSUE THREAD

**Issue by Alfrad** [bramp/ffmpeg-cli-wrapper#186]
I need run FFmpegExecutor, and return java.io.File, its possible?

**Comment by Euklios** [comment]
I might be missunderstanding your question, but it doesn't make sense for us to return the output files to you.

FFmpeg can create any number of multiple different output kinds.
Additionally, outputs don't have to be files.
And last, files created by ffmpeg might not be specified as output.

The best reference for what output files are created is the parameters when you pass to FFmpeg.
If you specify a single output that writes to a file, that's yours.

Feel free to re-open or create a new issue if there are any questions.
