### ISSUE TITLE
Wrap ffplay in addition to ffmpeg and ffprobe

### ISSUE THREAD

**Issue by teocci** [bramp/ffmpeg-cli-wrapper#189]
**Is your feature request related to a problem? Please describe.**
I was using JavaCV to play multiple audio and video streams. However, the audio gradually lags behind. I tried to achieve low-latency for real-time streams, but I only was able to reduce the delay to 300 ms but after 10 mins the delay increases to more 2 seconds.
On the other hand when I use the `ffplay` command the delay is near to 200 ms and it does not vary much after more than one hour of continues stream.
I was searching for a ffplay wrapper for Java but I didn't found a useful one.
**Describe the solution you'd like**
It will be nice to have a ffplay wrapper. I think the SoundDataLine introduce some delay  when it is playing the audio. I reduced the buffer size to 384 but it doesn't work. the delay increases gradually as the time pass.

**Describe alternatives you've considered**
I was using JavaCV it is great for the video. But the audio has this problem. I need to play multiple RTSP streams in real-time.

**Comment by bramp** [comment]
I think this is a great future idea, but no one any active maintainer is willing to implement. So I'm going to close. Feel free to reopen if you wish to submit a pull request to add the functionality.
