### ISSUE TITLE
audioFilter and videoFilter should be swapped

### ISSUE THREAD

**Issue by detistov** [bramp/ffmpeg-cli-wrapper#194]
**Describe the bug**

The option for videofilter in ffmpeg is -vf and for and for audio is -af. The values in the FFmpegBuilder should be swapped.

**To Reproduce**
```java
// Example code
```

**Expected behavior**

**Version (if applicable):**
 - OS: [e.g. Linux]
 - Java Version [e.g. 8]

**Additional context**

**Comment by slurba** [comment]
Just encountered this problem myself. Sounds like an easy fix since only the names need to be swapped. atm "setVideoFilter" sets audio filters and vice versa.

**Comment by aeromac** [comment]
In FFmpegBuilder, should be:

if (!Strings.isNullOrEmpty(videoFilter)) {
      args.add("-vf", videoFilter);
    }

    if (!Strings.isNullOrEmpty(audioFilter)) {
      args.add("-af", audioFilter);
    }

**Comment by Butzlabben** [comment]
What about is this issue? I could create an PR if wanted, but this issue seems rather trivial.

**Comment by Euklios** [comment]
@bramp This has been fixed in commit 94a8658
