### ISSUE TITLE
Issue with wrapper

### ISSUE THREAD

**Issue by arisprung18** [bramp/ffmpeg-cli-wrapper#205]
I am trying to use this and having some issues 

https://stackoverflow.com/questions/59154041/cant-stream-rtsp-feed-to-hls-from-java-wrapper

This command is working fine in the command line

ffmpeg -i 'rtsp://user:password@192.168.86.00/live' -acodec copy -vcodec copy -f hls -hls_flags delete_segments+append_list cam.m3u8
However when I attempt to use this using the java wrapper above I get the following error. Any idea?

CODE

        FFmpeg ffmpeg = new FFmpeg("/usr/local/Cellar/ffmpeg/4.2.1_2/bin/ffmpeg");
    FFprobe ffprobe = new FFprobe("/usr/local/Cellar/ffmpeg/4.2.1_2/bin/ffprobe");

    FFmpegBuilder builder =
            new FFmpegBuilder()
                    .setInput("rtsp://xxxx:xxxx@192.168.86.00/live")
                    .addExtraArgs("-acodec", "copy")
                    .addExtraArgs("-vcodec", "copy")
                    .addExtraArgs("-f", "hls")
                    .addExtraArgs("-safe", "0")
                    .addExtraArgs("-hls_flags", "delete_segments+append_list")
                    .addOutput("cam.m3u8")
                    .setFormat("cam.m3u8")
                    .done();
    builder.setVerbosity(FFmpegBuilder.Verbosity.DEBUG);

    FFmpegExecutor executor = new FFmpegExecutor(ffmpeg, ffprobe);

    // Run a one-pass encode
    executor.createJob(builder).run();
ERROR

 java.io.IOException: /usr/local/Cellar/ffmpeg/4.2.1_2/bin/ffmpeg returned non-zero exit status. Check stdout.

FFMPEG DEBUG LOGS
ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.8)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.1_2 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/adoptopenjdk-13.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-13.jdk/Contents/Home/include/darwin -fno-stack-check' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Splitting the commandline.
Reading option '-y' ... matched as option 'y' (overwrite output files) with argument '1'.
Reading option '-v' ... matched as option 'v' (set logging level) with argument 'debug'.
Reading option '-acodec' ... matched as option 'acodec' (force audio codec ('copy' to copy stream)) with argument 'copy'.
Reading option '-vcodec' ... matched as option 'vcodec' (force video codec ('copy' to copy stream)) with argument 'copy'.
Reading option '-f' ... matched as option 'f' (force format) with argument 'hls'.
Reading option '-safe' ... matched as AVOption 'safe' with argument '0'.
Reading option '-hls_flags' ... matched as AVOption 'hls_flags' with argument 'delete_segments+append_list'.
Reading option '-i' ... matched as input url with argument 'rtsp://xx:xx@192.168.86.95/live'.
Reading option '-f' ... matched as option 'f' (force format) with argument 'cam.m3u8'.
Reading option 'cam.m3u8' ... matched as output url.
Finished splitting the commandline.
Parsing a group of options: global .
Applying option y (overwrite output files) with argument 1.
Applying option v (set logging level) with argument debug.
Successfully parsed a group of options.
Parsing a group of options: input url rtsp://xx:xx@192.168.86.95/live.
Applying option acodec (force audio codec ('copy' to copy stream)) with argument copy.
Applying option vcodec (force video codec ('copy' to copy stream)) with argument copy.
Applying option f (force format) with argument hls.
Successfully parsed a group of options.
Opening an input file: rtsp://xx:xx@192.168.86.95/live.
Unknown decoder 'copy'

**Comment by bramp** [comment]
The order of the arguments matter. 'addExtraArgs("-acodec", "copy")' is being applied to the input, which in this case is not valid. You want it to be applied to the output.

Something like this may work better:

```java
FFmpegBuilder builder =
        new FFmpegBuilder()
                .setInput("rtsp://xxxx:xxxx@192.168.86.00/live")
                .addOutput("cam.m3u8")
                .addExtraArgs("-acodec", "copy")
                .addExtraArgs("-vcodec", "copy")
                .addExtraArgs("-f", "hls")
                .addExtraArgs("-safe", "0")
                .addExtraArgs("-hls_flags", "delete_segments+append_list")
                .done();
```

**Comment by arisprung18** [comment]
Thx! That worked!
