### ISSUE TITLE
"File not found" when run inside a .jar

### ISSUE THREAD

**Issue by sameda** [bramp/ffmpeg-cli-wrapper#207]
I used this library in my spring-boot application and it was running OK, but when I deployed the application with a jar file, compression stopped working as it expects to find the input file in the file system, whereas the file is located in the resources, inside the jar. Is there a solution for this, as the setInput() method  of the builder only accepts the file path, and not an InputStream for example?

**Comment by stormstricker** [comment]
Have you solved it?

**Comment by Katsute** [comment]
The library itself does not format files, it wraps the FFMPEG exe; meaning that since FFMPEG itself does not offer input streams as a valid input, the java library also can't offer the input stream as an input.

**Comment by dfernandezm** [comment]
Would it be valid writing a temporary file del the InputStream, and delete on exit?

**Comment by Euklios** [comment]
> Would it be valid writing a temporary file from the InputStream, and delete on exit?

This is currently being implemented in #334
As the original question seems to be answered, I'll close this issue for now.
