### ISSUE TITLE
How to make the wrapper less verbose ?

### ISSUE THREAD

**Issue by caaiofarias** [bramp/ffmpeg-cli-wrapper#208]
How i remove the INFO log from RunProcessor ? 

`[main] INFO net.bramp.ffmpeg.RunProcessFunction - /usr/bin/ffmpeg -version`

**Comment by RakSrinaNa** [comment]
You can probably filter these out from the configuration of your logger (log4j, logback, ...) by setting `net.bramp.ffmpeg` to a level of `WARN` for example.
