### ISSUE TITLE
Unknown decoder 'h264_cuvi'

### ISSUE THREAD

**Issue by chenchen1992223** [bramp/ffmpeg-cli-wrapper#221]
I use the GPU version of ffmpeg, which can be executed with commands on Linux, but an error is reported on the Java API, unknown decoder 'H264'_ Cuvi ', I see that the commands printed by Java API are consistent with those manually executed in Linux. Does the API not support GPU parameters

**Comment by bramp** [comment]
This Java Library just wraps the command line. So the decoders supported by the command line, are also supported by the library.

Can you share some code? And perhaps we can debug?

**Comment by chenchen1992223** [comment]
I have compared the command again. It is the command I executed in Java is wrong. Thank you for your reply

> This Java Library just wraps the command line. So the decoders supported by the command line, are also supported by the library.
> 
> Can you share some code? And perhaps we can debug?

I have compared the command again. It is the command I executed in Java is wrong. Thank you for your reply
