### ISSUE TITLE
Is LAME Mp3 library supported?

### ISSUE THREAD

**Issue by barbetb** [bramp/ffmpeg-cli-wrapper#222]
Is LAME library supported so we can convert to mp3's? That would be a really really nice feature. 

Execute stuff like:
```
ffmpeg -i inputfile.m4a -c:a libmp3lame -ac 2 -q:a 2 outputfile.mp3
ffmpeg -i inputfile.m4a -c:a libmp3lame -ac 2 -b:a 190k outputfile.mp3
```
It shouldn't be to hard right?

**Comment by Euklios** [comment]
This is just a wrapper arround the FFmpeg executable.
If the LAME library is supported the FFmpeg executable you referenced when calling `new FFmpeg()` (or the one from your path if no parameter is given), then this library will support it as well.
