### ISSUE TITLE
Question: split video to small parts of constant time using ffmpeg-cli-wrapper

### ISSUE THREAD

**Issue by gennadyg** [bramp/ffmpeg-cli-wrapper#227]
**The question**
Trying to use ffmpeg-cli-wrapper in order to split video to a group of short videos with the same time, for instance if I have video that play 55 sec and want to split it to 10 sec parts, expected to receive 6 parts where last only have 5 sec 

**Example ffmpeg command**
```shell
ffmpeg -i input.mp4 -c copy -map 0 -segment_time 00:10:00 -f segment output%03d.mp4
```

Will appreciate any help.

**Comment by Euklios** [comment]
This should now be possible, thanks to #322 
Feel free to re-open if this is not the case.
