### ISSUE TITLE
Unable to add -safe 0 argument before input

### ISSUE THREAD

**Issue by dsvensson** [bramp/ffmpeg-cli-wrapper#228]
Related to #199, when using absolute paths you need `-safe 0` before `-f concat` which is not possible today.

**Comment by Euklios** [comment]
This should be possible now, thanks to #339.
I'm not sure however, how exactly the "-safe" option is applied.

The code:
```java
new FFmpegBuilder()
            .addExtraArgs("-safe", "0")
            .addInput("in.mp4")
            .setFormat("concat")
            .done()
            .addOutput("out.mp4")
            .done()
            .build()
```

would produce the command `ffmpeg -y -v error -safe 0 -f concat -i in.mp4 out.mp4`.
However, `-safe` is treated as an argument for the entire ffmpeg execution.

The code:
```java
new FFmpegBuilder()
            .addInput("in.mp4")
            .addExtraArgs("-safe", "0")
            .setFormat("concat")
            .done()
            .addOutput("out.mp4")
            .done()
            .build()
```

Would produce `ffmpeg -y -v error -f concat -safe 0 -i in.mp4 out.mp4`.

I hope this solves the problem you described here.
If not, please re-open and provide me with a command demonstrating what you'd like to build.
If possible, use two inputs, as this would make the usage of `-safe` much more clearer.
