### ISSUE TITLE
Using ffmpeg-cli-wrapper for streaming I need the -f switch to be applied to the output

### ISSUE THREAD

**Issue by SiKing** [bramp/ffmpeg-cli-wrapper#234]
**The question**
I would like to use the ffmpeg-cli-wrapper for simple streaming of a video. I am a first-time user of ffmpeg, and I came up with the below code.

From the error and from my examination (details below) it appears the `-f {format}` is applied to the input, but I need it applied to the output.

What am I doing wrong? How do I get a simple stream to work?

**Example ffmpeg command**
```shell
ffmpeg -i big_buck_bunny_720p_1mb.mp4 -f flv "rtmp://myserver.box/stream"
```

**What you have tried**
Using [FFmpegExecutorTest](https://github.com/bramp/ffmpeg-cli-wrapper/blob/master/src/test/java/net/bramp/ffmpeg/FFmpegExecutorTest.java) as a roadmap, I came up with the following:

```java
FFmpeg ffmpeg = new FFmpeg();
FFprobe ffprobe = new FFprobe();
FFmpegExecutor ffExecutor = new FFmpegExecutor(ffmpeg, ffprobe);
ExecutorService executor = Executors.newSingleThreadExecutor();

ClassLoader classLoader = getClass().getClassLoader();
String input = classLoader.getResource("data/big_buck_bunny_720p_1mb.mp4").getFile();
URI output = new URI("rtmp://myserver.box/stream");

FFmpegBuilder builder = new FFmpegBuilder();
builder.setInput(input);
builder.setFormat("flv");
builder.addOutput(output);
builder.build();
FFmpegJob job = ffExecutor.createJob(builder);
executor.submit(job).get();
```

When I run this, I get the following error:

```
14:24:53.692-0700 [pool-1-thread-1] [INFO] RunProcessFunction - ffmpeg -y -v error -f flv -i {redacted}/target/test-classes/data/big_buck_bunny_720p_1mb.mp4 rtmp://myserver.box/stream
{redacted}/target/test-classes/big_buck_bunny_720p_1mb.mp4: could not find codec parameters
```

However, if on the command line if I switch the `-f` and `-i` options around, so that the order is: `-i <project>/target/test-classes/data/big_buck_bunny_720p_1mb.mp4 -f flv rtmp://myserver.box/stream` then everything works as expected.

**Comment by SiKing** [comment]
From [documentation](https://ffmpeg.org/ffmpeg.html#Description):

> As a general rule, options are applied to the next specified file. Therefore, order is important, and you can have the same option on the command line multiple times. Each occurrence is then applied to the next input or output file.

**Comment by zilzurna** [comment]
Check out this streaming example of video.
https://github.com/bramp/ffmpeg-cli-wrapper/blob/master/src/test/java/net/bramp/ffmpeg/ExamplesTest.java#L40

**Comment by SiKing** [comment]
Thanx for the help.

In order to get my usecase to work, I found the following:

1. The ordering is not intuitive. If I want the format to be applied to the output, the order **must** be like this:
```java
FFmpegBuilder builder = new FFmpegBuilder(). //
        setFormat(inputFormat). // input
        setInput(input). //
        addOutput(output). //
        setFormat("flv"). // must come AFTER the output
        done();
```
Something like this will not work correctly, even though this might look like the order you would specify for ffmpeg on the CLI.
```java
FFmpegBuilder builder = new FFmpegBuilder(). //
        setFormat(inputFormat). // input
        setInput(input). //
        setFormat("flv"). // output
        addOutput(output). //
        done();
```

2. Code form - not sure what to call this. The following will always give the wrong result!
```java
FFmpegBuilder builder = new FFmpegBuilder();
builder.setFormat(inputFormat);
builder.setInput(input);
builder.addOutput(output);
builder.setFormat("flv");
builder.build();
```
