### ISSUE TITLE
How can I keep the original video quality?

### ISSUE THREAD

**Issue by GdavidPaella** [bramp/ffmpeg-cli-wrapper#238]
**The question**

> I'd like to create an exact copy from a given audio or video file, keeping the quality, format, codec, framrate, bitrate, etc... (I just get bigger or smaller files, but can't get to get a file with the same attributes and size)

**What you have tried**

> I'm trying to remove settings hoping it takes the original file values.
> 
> I also tried:
> **.setConstantRateFactor(0)**
>

**Comment by GdavidPaella** [comment]
Solution: (In case someone has the same issue)

```
FFmpegBuilder builder = new FFmpegBuilder()
...
.setAudioCodec("copy")
.setVideoCodec("copy")
```

**Comment by Euklios** [comment]
Thank you for the issue and answer! I'll go ahead and close this issue, as you have answered it yourself.
Feel free to reopen or create a new issue.
