### ISSUE TITLE
ffpobe bitrate overflow int

### ISSUE THREAD

**Issue by asafbennatan** [bramp/ffmpeg-cli-wrapper#24]
hi ,
i'm getting json parsing error after running FFprobe.probe on some image,
turns out that ffprobe's output is : 
Input #0, image2, from 'C:\temp\templates\c41b4f90-3dc2-42c8-8efa-7dee15e19d01\(Footage)\Assets\back.jpg':
  Duration: 00:00:00.04, start: 0.000000, bitrate: 2510838 kb/s
    Stream #0:0: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 5760x3840 [SAR 300:300 DAR 3:2], 25 tbr, 25 tbn, 25 tbc

notice that the bitrate exceeds int ,
FFmpegFormat field bitrate should be changed to long

**Comment by bramp** [comment]
This was fixed in 2b264fd47e6f88b36a8e3804c79f2f6f78254d70 and available since ffmpeg-0.3.

Please update, and if you still experience the issue please reopen. Thanks!
