### ISSUE TITLE
what i need to include in FFmpeg ffmpeg = new FFmpeg("/path/to/ffmpeg");  path to file ffmpeg Lunux

### ISSUE THREAD

**Issue by mikebgrep** [bramp/ffmpeg-cli-wrapper#240]
I have a question what i need to write in path to ffmpeg in Lunux Ubuntu actually Is executable file or something else 
Do I need to do make install or only make for ffmpg source https://launchpad.net/ubuntu/+source/ffmpeg/7:4.4.1-1ubuntu2
```
FFmpeg ffmpeg = new FFmpeg("/path/to/ffmpeg");
FFprobe ffprobe = new FFprobe("/path/to/ffprobe");

```

**Comment by bramp** [comment]
Yes the path to the executable.

Type `which ffmpeg` in a terminal, and that value is what you will use.

**Comment by mikebgrep** [comment]
Okay thank you I didn't know this command

**Comment by Goldo02** [comment]
I get this error: This binary '/usr/local/bin/ffmpeg' is not a supported version of ffprobe

**Comment by bramp** [comment]
"his binary '/usr/local/bin/ffmpeg' is not a supported version of ffprobe"... did you mean to use /usr/local/bin/**ffprobe** ?

**Comment by bramp** [comment]
I think this issue is resolve. Feel free to reopen if you need more help. Thanks.
