### ISSUE TITLE
How to start an RTSP Publish from a device on linux? 

### ISSUE THREAD

**Issue by TriageONE** [bramp/ffmpeg-cli-wrapper#243]
**The question**
I have been attempting to make this work for some time now, and i have a specific command i would traditionally use in order to start an RTSP publish action with FFMPEG normally. The command would look like this: 
```ffmpeg -f v4l2 -i /dev/video0 -c:v libx264 -preset fast -b:v 600k -f rtsp rtsp://<url and path>```
This command works perfectly when ran by itself
my question is, is the builder settings im using below copy 1:1 with the above? 

```
FFmpegBuilder builder = new FFmpegBuilder()

                    .setInput(inputDevice)     // Filename, or a FFmpegProbeResult
                    .setFormat("v4l2")           // the format for grabbing from a camera 

                    .addOutput(outputUrl)   // Filename for the destination
                    .setVideoCodec("libx264") //codec
                    .setPreset("fast")  //fast preset
                    .setVideoBitRate(600)  //bitrate of 600K
                    .setFormat("rtsp") //format for output URL 

                    .done();

builder.addStdoutOutput();
FFmpegExecutor executor = new FFmpegExecutor(ffmpeg, ffprobe);
executor.createJob(builder).run();
```

The below is the output from the terminal when it attempts to start the video. The camera in question attached to video0 is in fact connected, and the output url here is in fact working. **Using the command above in CLI** I can publish normally and see it in docker on the main server, as well as on VLC if i open the stream. 

```
[NULL @ 0x17eb060] Unable to find a suitable output format for 'pipe:'
pipe:: Invalid argument
Exception in thread "Thread-0" java.lang.RuntimeException: java.io.IOException: /usr/bin/ffmpeg returned non-zero exit status. Check stdout.
        at net.bramp.ffmpeg.job.SinglePassFFmpegJob.run(SinglePassFFmpegJob.java:46)
        at util.StreamThread.run(StreamThread.java:42)
Caused by: java.io.IOException: /usr/bin/ffmpeg returned non-zero exit status. Check stdout.
        at net.bramp.ffmpeg.FFcommon.throwOnError(FFcommon.java:51)
        at net.bramp.ffmpeg.FFcommon.run(FFcommon.java:113)
        at net.bramp.ffmpeg.FFmpeg.run(FFmpeg.java:184)
        at net.bramp.ffmpeg.FFmpeg.run(FFmpeg.java:202)
        at net.bramp.ffmpeg.job.SinglePassFFmpegJob.run(SinglePassFFmpegJob.java:39)
        ... 1 more
```

**What you have tried**
Ive tried removing certain parts and attempting to find alternatives, but that stacktrace tells me nothing about what i did wrong. I cant find the root cause of the issue because nothing pertaining to my code is present here.

**Comment by bramp** [comment]
I'm pretty sure `[NULL @ 0x17eb060] Unable to find a suitable output format for 'pipe:'` is coming from ffmpeg itself, but I don't see the word `pipe` anywhere in your example. What is the outputUrl?

Also if you do `builder.build()` you'll get back a List<String> of the command that would be run. That would be useful to see.

**Comment by TriageONE** [comment]
The output url of the last time I ran this looked like `rtsp://triagecore.com:8443/0000-0000-0000/S0`

**Comment by TriageONE** [comment]
> I'm pretty sure `[NULL @ 0x17eb060] Unable to find a suitable output format for 'pipe:'` is coming from ffmpeg itself, but I don't see the word `pipe` anywhere in your example. What is the outputUrl?
> 
> Also if you do `builder.build()` you'll get back a List of the command that would be run. That would be useful to see.

 I did this and here is the output of builder.build();

`[-y, -v, error, -f, v4l2, -i, /dev/video1, -f, rtsp, -preset, fast, -vcodec, libx264, -b:v, 600, rtsp://triagecore.com:8554/0000-0000-0000/S1, -]`
It looks like there is some sort of dash at the end of the statement, and im not sure how to get rid of it. Any suggestions? there is no pipe however, so im not sure where this is coming from. The code above has not changed, and the program, using `System.out.println("Output url: " + this.outputUrl + ", Input Device:" + this.inputDevice);`  outputs `Output url: rtsp://triagecore.com:8554/0000-0000-0000/S1, Input Device:/dev/video1` in console. 

The full stacktrace is below: 
```
Output url: rtsp://triagecore.com:8554/0000-0000-0000/S1, Input Device:/dev/video1
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[-y, -v, error, -f, v4l2, -i, /dev/video1, -f, rtsp, -preset, fast, -vcodec, libx264, -b:v, 600, rtsp://triagecore.com:8554/0000-0000-0000/S1, -]
[NULL @ 0xf69060] Unable to find a suitable output format for 'pipe:'
pipe:: Invalid argument
Exception in thread "Thread-0" java.lang.RuntimeException: java.io.IOException: /usr/bin/ffmpeg returned non-zero exit status. Check stdout.
        at net.bramp.ffmpeg.job.SinglePassFFmpegJob.run(SinglePassFFmpegJob.java:46)
        at util.StreamThread.run(StreamThread.java:43)
Caused by: java.io.IOException: /usr/bin/ffmpeg returned non-zero exit status. Check stdout.
        at net.bramp.ffmpeg.FFcommon.throwOnError(FFcommon.java:51)
        at net.bramp.ffmpeg.FFcommon.run(FFcommon.java:113)
        at net.bramp.ffmpeg.FFmpeg.run(FFmpeg.java:184)
        at net.bramp.ffmpeg.FFmpeg.run(FFmpeg.java:202)
        at net.bramp.ffmpeg.job.SinglePassFFmpegJob.run(SinglePassFFmpegJob.java:39)
        ... 1 more
```

**Comment by TriageONE** [comment]
I believe i have fixed the issue. The problem was certainly because of the dash, however the dash's cause was because of this line, which i apologise for not providing in the code i gave. It seemed irrelevant because of its nature, so i naturally ignored it. 
            `builder.addStdoutOutput();`

This line alone at the end of my statement managed to emplace that dash. Removing the code above entirely then allowed the program to run.

**Comment by bramp** [comment]
ah doh!   addStdoutOutput will make your output go to stdout.  I wonder if I can detect that, and make addStdoutOutput fail in this particular scenario.
