### ISSUE TITLE
Any Success Example Add watermark

### ISSUE THREAD

**Issue by suhakopan** [bramp/ffmpeg-cli-wrapper#248]
Hi, 

While browsing the test codes, I tried adding watermark to the video. But I did not get any successful results.

![image](https://user-images.githubusercontent.com/34922338/167411875-adc0208e-ab56-44db-8ebd-fd9ba5c549d3.png)

**First error;**

- java.lang.IllegalStateException: Target size does not support multiple inputs

**After delete setTargetSize()**

- java.lang.IllegalArgumentException: Target size, or video bitrate must be specified when using two-pass

Anybody have success example to add a watermark on video?

**Comment by harrymaurya05** [comment]
Hi @suhakopan @bramp 
Here is the code spinet to add watermark on video.

`@Test
  public void addWaterMarkTest() throws IOException{
    FFmpegExecutor executor = new FFmpegExecutor(ffmpeg, ffprobe);

    FFmpegProbeResult in = ffprobe.probe("/home/hariom/Downloads/video.mp4");
    FFmpegProbeResult inImage = ffprobe.probe("/home/hariom/Downloads/download.jpeg");
    FFmpegBuilder builder = new FFmpegBuilder()
            .setInput(in)
            .overrideOutputFiles(true)
            .addInput(inImage)
            .overrideOutputFiles(true)
            .addOutput("output1.mp4")
            .done().setComplexFilter("overlay=10:10");

    FFmpegJob job =
            executor.createJob(
                    builder,
                    new ProgressListener() {

                      // Using the FFmpegProbeResult determine the duration of the input
                      final double duration_ns = in.getFormat().duration * TimeUnit.SECONDS.toNanos(1);

                      @Override
                      public void progress(Progress progress) {
                        double percentage = progress.out_time_ns / duration_ns;

                        // Print out interesting information about the progress
                        System.out.println(
                                String.format(
                                        locale,
                                        "[%.0f%%] status:%s frame:%d time:%s fps:%.0f speed:%.2fx",
                                        percentage * 100,
                                        progress.status,
                                        progress.frame,
                                        FFmpegUtils.toTimecode(progress.out_time_ns, TimeUnit.NANOSECONDS),
                                        progress.fps.doubleValue(),
                                        progress.speed));
                      }
                    });

    job.run();

    assertEquals(FFmpegJob.State.FINISHED, job.getState());
  }`
