### ISSUE TITLE
Does this project support S3? Upload directly to the s3 bucket instead of in-memory

### ISSUE THREAD

**Issue by DevOpsRealm** [bramp/ffmpeg-cli-wrapper#249]
The ffmpeg-cli-wrapper library is a simple wrapper around the ffmpeg command line. If you have questions on how to use the library, please check out the [usage](https://github.com/bramp/ffmpeg-cli-wrapper#usage), or [random examples](https://github.com/bramp/ffmpeg-cli-wrapper/wiki/Random-Examples). If that doesn't solve your problem please fill out the following:

**The question**
A clear and concise description of what you are trying to acheive.

**Example ffmpeg command**
```shell
ffmpeg -i input.mp4 output.mp4
```

**What you have tried**
What you have tried so far, with example code, or error messages.

**Comment by bramp** [comment]
This project is a wrapper around the ffmpeg cli tool. If it can upload to S3, then we can.

Otherwise if we want to write into memory, and this library write into S3, that would be out of scope.
