### ISSUE TITLE
Add additional CodecTypes to FFmpegStream

### ISSUE THREAD

**Issue by Euklios** [bramp/ffmpeg-cli-wrapper#264]
**Is your feature request related to a problem? Please describe.**
I need to recognize ass subtitles within video files.
ASS often uses additional font files embedded within the video itself.
I need to differentiate between the subtitle streams, and the attached font files

**Describe the solution you'd like**
Add additional CodecTypes to FFmpegStream for:
 - Subtitle
 - Attachment

**Describe alternatives you've considered**
I don't think it's possible to solve this issue without reimplementing the corresponding objects.

**Comment by Euklios** [comment]
Relates to #259

**Comment by Anilkumar-Shrestha** [comment]
waiting for this to be released. :)
