### ISSUE TITLE
Mind changing license from BSD2 to Apache2 or MIT?

### ISSUE THREAD

**Issue by vladimirshefer** [bramp/ffmpeg-cli-wrapper#272]
**The question**
Dont you mind to change to the free to use license like Apache2 or MIT?

I'd like to use this library in my pet projects, which i'd like to distribute under Apache2 license, but your license prevents me from doing that.

**Comment by bramp** [comment]
Sorry, I think this project has had too many external contributions, for me to solely decide to unilaterally change the license.
