### ISSUE TITLE
Error while installing FFmpeg Java

### ISSUE THREAD

**Issue by ImFedehh** [bramp/ffmpeg-cli-wrapper#279]
**Describe the bug**
it seems that the plugin "maven-gpg-plugin" was unable for some reason to complete the ffmpeg project artifact signing operation due to an error generated by gpg.

**To Reproduce**
```
run mvn install in the ffmpeg-cli-wrapper-master directory (the error also happen if you run Building & Releasing commands)
```

**Expected behavior**
theoretically it should compile the final .jar file to use as an external library.

**Version (if applicable):**
 - OS: macOS (intellij idea 2022.3.1)
 - Java Version: openjdk 19.0.1 2022-10-18
 - gpg (GnuPG) 2.4.0
 - Apache Maven 3.8.7
  
**Additional context**
12:53:27.460 [TcpProgressParser(tcp://127.0.0.1:49170)] WARN net.bramp.ffmpeg.progress.Progress - skipping unhandled key: out_time_us = 5269333 (and other similar warnings)
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:3.0.1:sign (sign-artifacts) on project ffmpeg: Exit code: 2 -> [Help 1]

Please let me know if I'm doing something wrong and if there's a way to fix it. 
Thank you.

**Comment by bramp** [comment]
I haven't updated the plugins in a while. Maybe that would help... But a quick Google search, shows others with a similar issue and fixes: https://stackoverflow.com/a/54325356/88646

**Comment by bramp** [comment]
I've updated a bunch of things, and been unable to repro this myself. If this is still a problem please reopen this thread.
