### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by jaume-pinyol** [bramp/ffmpeg-cli-wrapper#293]
Hi,
Is there any option to release a newer version?, there are some bugs and features that has been added into master since the last release(0.7.0) in April 2022 that are quite useful.

Thanks!

**Comment by nooblong** [comment]
+1

**Comment by bramp** [comment]
Released 0.8.0: https://central.sonatype.com/artifact/net.bramp.ffmpeg/ffmpeg/0.8.0
