### ISSUE TITLE
How to perform screen recorder using this library?

### ISSUE THREAD

**Issue by kumarkrish85** [bramp/ffmpeg-cli-wrapper#295]
The ffmpeg-cli-wrapper library is a simple wrapper around the ffmpeg command line. If you have questions on how to use the library, please check out the [usage](https://github.com/bramp/ffmpeg-cli-wrapper#usage), or [random examples](https://github.com/bramp/ffmpeg-cli-wrapper/wiki/Random-Examples). If that doesn't solve your problem please fill out the following:

**The question**
I want to perform screen recording along with audio and save the content as .mp4 file format. I can do it through ffmpeg commands

**Example ffmpeg command**
```shell
ffmpeg -hide_banner -loglevel error -f dshow -i audio="<device-name>" -f gdigrab -framerate 30 -i desktop -c:v libx264 %video_file_name%".mp4"
```

**What you have tried**
I don't find any examples, could you please help

**Comment by Euklios** [comment]
Closed thanks to #339.
I also just added a test for the command mentioned above
