### ISSUE TITLE
How can I extract the meta information of Video/Audio files?

### ISSUE THREAD

**Issue by vijayamurugan** [bramp/ffmpeg-cli-wrapper#3]
Does it has solution to extract the meta information of given audio/video files?

**Comment by bramp** [comment]
There is the FFProbe class https://github.com/bramp/ffmpeg-cli-wrapper/blob/gh-pages/src/main/java/net/bramp/ffmpeg/FFprobe.java

Sorry I appear to not have documented that in the README.

**Comment by vijayamurugan** [comment]
Thanks for the quick update. I will be working on this in next week. I will update back if I need any more meta info than those you have specified in Probe or I will tweak it and update back the code here.
