### ISSUE TITLE
Document how to use FFmpegProbeResult to get video properties (duration,size,dimension)

### ISSUE THREAD

**Issue by stonio** [bramp/ffmpeg-cli-wrapper#30]
Can you expose media information such as, duration, size, width, height reported by ffprobe?

So we could display these properties to end-users.

**Comment by bramp** [comment]
FFprobe already exposes this information. In what situation does it not?

**Comment by stonio** [comment]
You are right. I have just discovered nifty class `FFmpegProbeResult`.

**Comment by stonio** [comment]
Can you add an example of `FFmpegProbeResult` usage (i.e.: get video duration) in `README.md` ?
