### ISSUE TITLE
Compilation failure - "Could not determine gpg version"

### ISSUE THREAD

**Issue by jegsav** [bramp/ffmpeg-cli-wrapper#329]
I downloaded ffmpeg-cli-wrapper-master.zip from github, unpacked it and imported the contents into Netbeans 13 using the "Java with Maven" option and "Project with existing POM".

When I "Clean and Build", I get the following error:

Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:3.2.0:sign (sign-artifacts) on project ffmpeg: Could not determine gpg version -> [Help 1]

Of course I have tried to find a reason and solution to this on the internet, but couldn't find one. I am a complete novice with Maven, so help with this would be appreciated.

Thanks.

**Comment by ankit0038** [comment]
I have resolved this issue, basically I had to set gpg on my system and generate keys, passphrase. and when building the project pass that phrase as argument -Dgpg.passphrase=<yourPassphrase>.

**Comment by jegsav** [comment]
Good to have found a solution, ankit0038, but I had got what I needed a long time ago. This second brush with Maven has confirmed my first experience that it's not for me - far to steep a learning curve and can't really see any benefit for what I do. But thanks anyway.
