### ISSUE TITLE
Codec type is null and HZ values are missing from streams

### ISSUE THREAD

**Issue by vijayamurugan** [bramp/ffmpeg-cli-wrapper#4]
Codectype , hz and stereo/Mono identifier are missing

I am expecting below values via FFProbe

Example:
 Metadata:
    artist          : Girl Talk (RoyalJatt.Com)
    album           : All Day (www.RoyalJatt.Com)
    genre           : RoyalJatt.Com
    date            : 2010
  Duration: 00:06:02.06, start: 0.000000, bitrate: 326 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, s16p, 320 kb/s
    Stream #0:1: Video: gif, bgra, 90k tbr, 90k tbn, 90k tbc
    Metadata:
      title           : cover
      comment         : Cover (front)

**Comment by vijayamurugan** [comment]
Hi Bramp, I have fixed the related issue. Shall I contribute back?

**Comment by bramp** [comment]
I would love a pull request. Including unit tests would also be great.

**Comment by bramp** [comment]
Hopefully fixed the codec_type in d50e3085a38425bee7178dfc8960bb49aa689588, and added tests in c9bcdb0e8cab16406cd1531e5 to ensure the hz and stereo/mono are correct.
