### ISSUE TITLE
Support time duration as string

### ISSUE THREAD

**Issue by stonio** [bramp/ffmpeg-cli-wrapper#43]
Library should support time duration set as string.

Example: Command `ffmpeg input.mp4 -ss 00:01 -t 00:04:55.267 output.mp4` from Java code `builder.setStartOffset("00:01").setDuration("00:04:55.267");`.

Reference: https://www.ffmpeg.org/ffmpeg-utils.html#Time-duration

**Comment by stonio** [comment]
We could implememnt static method `long FFmpegUtils#stringToMilliseconds(String)`.

```java
builder
	.setStartOffset(FFmpegUtils.stringToMilliseconds("00:01"))
	.setDuration(FFmpegUtils.stringToMilliseconds("00:04:55.267"));
```

**Comment by davinkevin** [comment]
@stonio You can use JODA or, better solution the official Java DateTime from java8 ( and also backported for older version, named ThreeTen -> http://www.threeten.org/) to do time calculation simply. 

I think what you want to do is converting the TimeUnit of a `Duration`, which is trivial with those API.

**Comment by bramp** [comment]
I'm going to close this. I don't want to reimplement FFmpeg's time/duration parsing.
