### ISSUE TITLE
how to merge some videos

### ISSUE THREAD

**Issue by Ive4** [bramp/ffmpeg-cli-wrapper#49]
how to merge some vedios?

**Comment by bramp** [comment]
Currently this is not possible.

You can do the following:
```
    List<String> args = new FFmpegBuilder()
        .addInput("input1")
        .addInput("input2")
        .addOutput("output.mp4")
          .done()
        .build();
```

But that won't do what I think you are asking. I'm going to say without additional changes, we can't concat videos together.

I'll turn this into a feature request.

**Comment by davinkevin** [comment]
Or you can do something like this : https://github.com/davinkevin/Podcast-Server/blob/master/Backend/src/main/java/lan/dk/podcastserver/service/FfmpegService.java

```java
try {
            Files.deleteIfExists(target);
            
            // Creation of string containing all input file ordered
            String filesStrings = Lists.newArrayList(files)
                    .stream()
                    .map(f -> f.getFileName().toString())
                    .map(p -> "file '" + p + "'")
                    .collect(joining(System.getProperty("line.separator")));

            // Saving this in a temp file
            listOfFiles = Files.createTempFile(target.getParent(), "ffmpeg-list-", ".txt");
            Files.write(listOfFiles, filesStrings.getBytes());

            // Used this txt file as input
            FFmpegBuilder builder = new FFmpegBuilder()
                    .setInput(listOfFiles.toAbsolutePath().toString())
                    .setFormat(FORMAT_CONCAT)
                    .addOutput(target.toAbsolutePath().toString())
                    .setAudioCodec(CODEC_COPY)
                    .setVideoCodec(CODEC_COPY)
                    .done();

            fFmpegExecutor.createJob(builder).run();

        } catch (IOException e) {
            log.error("Error during Ffmpeg concat", e);
        } finally {
            Path finalListOfFiles = listOfFiles;
            if (nonNull(listOfFiles)) Try.of(() -> Files.deleteIfExists(finalListOfFiles)); 
}
```

**Comment by bramp** [comment]
Oh awesome example. So it is possible using the concat format and copy codec.

Closing this as it is possible.

**Comment by AlpacaMan233** [comment]
> Or you can do something like this : https://github.com/davinkevin/Podcast-Server/blob/master/Backend/src/main/java/lan/dk/podcastserver/service/FfmpegService.java
> 
> ```java
> try {
>             Files.deleteIfExists(target);
> 
>             // Creation of string containing all input file ordered
>             String filesStrings = Lists.newArrayList(files)
>                     .stream()
>                     .map(f -> f.getFileName().toString())
>                     .map(p -> "file '" + p + "'")
>                     .collect(joining(System.getProperty("line.separator")));
> 
>             // Saving this in a temp file
>             listOfFiles = Files.createTempFile(target.getParent(), "ffmpeg-list-", ".txt");
>             Files.write(listOfFiles, filesStrings.getBytes());
> 
>             // Used this txt file as input
>             FFmpegBuilder builder = new FFmpegBuilder()
>                     .setInput(listOfFiles.toAbsolutePath().toString())
>                     .setFormat(FORMAT_CONCAT)
>                     .addOutput(target.toAbsolutePath().toString())
>                     .setAudioCodec(CODEC_COPY)
>                     .setVideoCodec(CODEC_COPY)
>                     .done();
> 
>             fFmpegExecutor.createJob(builder).run();
> 
>         } catch (IOException e) {
>             log.error("Error during Ffmpeg concat", e);
>         } finally {
>             Path finalListOfFiles = listOfFiles;
>             if (nonNull(listOfFiles)) Try.of(() -> Files.deleteIfExists(finalListOfFiles)); 
> }
> ```

What is CODEC_COPY?

**Comment by kingwsi** [comment]
This conflicts with ".overrideOutputFiles(true)"！
