### ISSUE TITLE
Set process builder's working directory

### ISSUE THREAD

**Issue by stonio** [bramp/ffmpeg-cli-wrapper#56]
We should be able to set [process builder's working directory](https://docs.oracle.com/javase/7/docs/api/java/lang/ProcessBuilder.html#directory%28java.io.File%29).

It's notably useful for writing two-pass log files at specific location.

**Comment by bramp** [comment]
The FFmpeg object calls its `ProcessFunction runFunction` to determine how to invoke ffmpeg. The ProcessFunction could create a local Process, could invoke some kind of network service, or could just do nothing (for example during testing). For you to do what you want, you can do the following:

```java
    RunProcessFunction func = new RunProcessFunction();
    func.setWorkingDirectory("/path/to/working/dir");

    FFmpeg ffmpeg = new FFmpeg("/path/to/ffmpeg", func);
    FFprobe ffprobe = new FFprobe("/path/to/ffprobe", func);

    FFmpegBuilder builder =
        new FFmpegBuilder()
            .setInput("input")
            .addOutput("output.mp4")
            .done();

    FFmpegExecutor executor = new FFmpegExecutor(ffmpeg, ffprobe);

    // Run a two-pass encode
    executor.createTwoPassJob(builder).run();
```
