### ISSUE TITLE
FFmpegBuilder API is not intuitive

### ISSUE THREAD

**Issue by henrydev10** [bramp/ffmpeg-cli-wrapper#64]
It seems that after `addOutput("filename")` another builder is returned - `FFmpegOutputBuilder`.

In my opinion the `FFmpegOutputBuilder` should be self contained builder, and `FFmpegBuilder` should have a method `public FFmpegBuilder addOutputBuilder(FFmpegOutputBuilder outputBuilder)`.

This will be much clearer, builder which returns itself and not another builder. Since once another builder is returned, there is no going back to the `FFmpegBuilder`.

This will also simplify multiple output creations on the consumer side, if there are repetitions with slight variations of the output, e.g. video format.

**Comment by bramp** [comment]
Thanks for your feedback. I debated a few different implementations of supporting the OutputBuilder. However, I think you missed the done() method to go back to the original builder, for example:

```java
List<String> args = new FFmpegBuilder()
  .setInput("input.mp4")     // Filename, or a FFmpegProbeResult

  .addOutput("output.mp4")   // Filename for the destination
    .setFormat("mp4")        // Format is inferred from filename, or can be set
    .setVideoCodec("libx264")     // Video using x264
    .done()

  .addOutput("output.flv")   // Filename for the destination
    .setFormat("flv")        // Format is inferred from filename, or can be set
    .done()

  .build();
```

If I understand your proposal you would prefer something like:
```java
List<String> args = new FFmpegBuilder()
  .setInput("input.mp4")     // Filename, or a FFmpegProbeResult

  .addOutput(new FFmpegOutputBuilder()
    .setName("output.mp4") // Filename for the destination
    .setFormat("mp4")        // Format is inferred from filename, or can be set
    .setVideoCodec("libx264")     // Video using x264
  )   

  .addOutput(new FFmpegOutputBuilder()
    .setName("output.flv")   // Filename for the destination
    .setFormat("flv")        // Format is inferred from filename, or can be set
  )

  .build();
```

**Comment by henrydev10** [comment]
Sorry, yes, I missed the `done` functionality. If this exists, my proposal is lowers in priority.

Your elaboration of my proposal is correct.
This can simplify your example to the following:

```java
List<String> args = new FFmpegBuilder()
   .setInput("input.mp4")     // Filename, or a FFmpegProbeResult

  .addOutput(createMP4Builder(15))    // with 15 FPS 
  .addOutput(createMP4Builder(30)     // with diff FPS
  .addOutput(createFLVBuilder())      // diff format 
  .build();
```

**Comment by bramp** [comment]
So it turns out with very minimal changes, and without breaking the API, I was able to make this work.  To avoid confusion, this won't be the main way used in the examples, but it will be documented, and tested.

**Comment by henrydev10** [comment]
Wow, thanks for the enhancement, looks great :)
