### ISSUE TITLE
Ability to skip defining inputs and do it manually via extra args

### ISSUE THREAD

**Issue by YuriMalinov** [bramp/ffmpeg-cli-wrapper#65]
Right now it's required to provide at least one input. I've got situation when:
1. input definition is complex: `-f lavfi -i aevalsrc=0`
2. it has to be before `extra_args` because they refer to it (`-map`, `-shortest`)

There was no way to do it besides extending `FFmpegBuilder` and just copying this method commenting out inputs check - and this way it worked well just with all args defined through `addExtraArgs`.

Maybe I'm missing something in ffmpeg usage - I've tried several args order in command line and it complained about `-i` going after other args.

**Comment by bramp** [comment]
Thanks for the report. Would you provide me an example of a full command line, so I can fully understand the issue.

**Comment by YuriMalinov** [comment]
Thanks for reply.. I should have posted command before.

I'm solving following problem: there are several videos, some with audio, some without and I need to concat them into one larger video.

To do so first I copy videos without sound stream adding to them null audio stream, command looks like this:
`ffmpeg.exe -y -v error -f lavfi -i aevalsrc=0 -i 1.mp4 -vcodec copy -acodec aac -map 0:0 -map 1:0 -shortest 1-no-audio.mp4`

Some parts are kind of magic for me now, so maybe there are better ways. At least `-f lavfi -i aevalsrc=0` is kind of single thing which shouldn't be split into parts. And also -map requires input to be defined before.

Changing order to something like
`ffmpeg.exe -y -v error -vcodec copy -acodec aac -map 0:0 -map 1:0 -shortest -f lavfi -i aevalsrc=0 -i 1.mp4 1-no-audio.mp4`
or `ffmpeg.exe -y -v error -f lavfi -i aevalsrc=0 -vcodec copy -acodec aac -map 0:0 -map 1:0 -shortest -i 1.mp4 1-no-audio.mp4`
breaks things with error like "Option map (set input stream mapping) cannot be applied to input file 1.mp4 -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to".

**Comment by igracia** [comment]
Perhaps #75 would solve this?

**Comment by Euklios** [comment]
Closed thanks to #339.
I also just added a test for the command mentioned above
