### ISSUE TITLE
How to set -pix_fmt?

### ISSUE THREAD

**Issue by hemanthsridhar** [bramp/ffmpeg-cli-wrapper#66]
I need to set -pix_fmt yuv420p using your APIs. How do I do it?

I am completely dependent on this. Please help me out if at there is an option. I am not able to set it.

**Comment by hemanthsridhar** [comment]
Any update on this?

**Comment by bramp** [comment]
There is no native support for setting pix_fmt, but you should be able to use [addExtraArgs](https://bramp.github.io/ffmpeg-cli-wrapper/net/bramp/ffmpeg/builder/FFmpegOutputBuilder.html#addExtraArgs-java.lang.String...-). For example:
```java
FFmpegBuilder builder = new FFmpegBuilder()
    .setInput("input.mp4")     // Filename, or a FFmpegProbeResult
    .addOutput("output.mp4")   // Filename for the destination
      .setFormat("mp4")        // Format is inferred from filename, or can be set

      .setVideoCodec("libx264")            // Video using x264
      .addExtraArgs("-pix_fmt", "yuv420p") // Extra ouput arg `-pix_fmt yuv420p'
      .done();

System.out.println(builder.build());
// Prints:
// [-y, -v, error, -i, input.mp4, -f, mp4, -vcodec, libx264, -pix_fmt, yuv420p, output.mp4]
```

Which should do what you want.

**Comment by hemanthsridhar** [comment]
@bramp  thank you so much

**Comment by hemanthsridhar** [comment]
@bramp  how to create the quality of the video?
