### ISSUE TITLE
take screens from video

### ISSUE THREAD

**Issue by Nasibulloh** [bramp/ffmpeg-cli-wrapper#71]
Please hepl me . how can i take screens from video

**Comment by bramp** [comment]
Hi Nasibulloh, for now the ffmpeg-cli-wrapper just makes it easy to call the ffmpeg command line. Do you have an example ffmpeg command line that would generate the screenshots you need? If you provide me the command, I can tell you how to use the library.

**Comment by Nasibulloh** [comment]
Hi. the thing is I do not need command line operation. I need Java API to
get the screenshots. Is it possible to do that with ffmpeg-cli-wrapper just
like we use ffmpeg Builder, ffmpegProbeResult and etc


2016-10-28 7:56 GMT+05:00 Andrew Brampton <notifications@github.com>:

**Comment by bramp** [comment]
So ffmpeg-cli-wrapper just calls out to the FFmpeg command line tool. I would suggest you figure out how to invoke ffmpeg to take the screenshot, and save it as a png. (Hint [stackoverflow](http://stackoverflow.com/questions/27568254/how-to-extract-1-screenshot-for-a-video-with-ffmpeg-at-a-given-time) has answers) Then you could load the png into your program using the [ImageIO API](https://docs.oracle.com/javase/7/docs/api/javax/imageio/ImageIO.html).

Alternatively, I'm working on a way to read a video directly into java as part of as part of bug #69. There is code already, I would consider it experimental. Instead, I suggest you try my first suggestion.

**Comment by amininama** [comment]
Hey!
Thanks for the awesomeness.
So, is it possible to run something like this using this API?
ffmpeg -ss 01:23:45 -i input -vframes 1 -q:v 2 output.jpg

I figured You closed issue #69, does it mean We're able to take screenshots directly?

**Comment by LinGoWei** [comment]
@amininama https://github.com/bramp/ffmpeg-cli-wrapper/wiki/Random-Examples 
you can look at Example 3, it is a take screens builder demo
