### ISSUE TITLE
Examples good quality ogv and webm?

### ISSUE THREAD

**Issue by yeahbutwalter** [bramp/ffmpeg-cli-wrapper#73]
I'm taking a very large mp4/mov file and I want to transcode it into three different formats for cross browser compatibility. I also watermark the video. First I create a smaller watermarked mp4 with h264, and it looks great;

    FFmpegBuilder builder = new FFmpegBuilder()

        .setInput(inVideo)     // Filename, or a FFmpegProbeResult
        .addInput(sampleWatermarkImg)
        .overrideOutputFiles(true) // Override the output if it exists
        .addOutput(destFile)   // Filename for the destination
        .setFormat("mp4")        // Format is inferred from filename, or can be set
        .setVideoCodec("libx264")     // Video using x264
        .setVideoFrameRate(24, 1)     // at 24 frames per second
        .setVideoResolution( iwidth , newHeight) // at 640x480 resolution
        .setComplexVideoFilter("\"overlay=main_w-overlay_w-10:main_h-overlay_h-10\"")
        .setStrict(FFmpegBuilder.Strict.EXPERIMENTAL) // Allow FFmpeg to use experimental specs
        .done();

When creating ogv with libtheora and webm with libvpx it looks terrible. Can you please give a hint as to how to set the quality? For ogv I want to set something like -qscale:v 7.

**Comment by bramp** [comment]
qscale:v isn't one of the supported arguments however, for anything that isn't explicitly supported (yet), you can call `.addExtraArgs("-qscale:v", "7")`, for example:

```java
// ffmpeg -i input.mkv -codec:v libtheora -qscale:v 7 -codec:a libvorbis -qscale:a 5 output.ogv
FFmpegBuilder builder = new FFmpegBuilder()
    .setInput("input.mkv")
    .addOutput("output.ogv")
      .setVideoCodec("libtheora")
      .addExtraArgs("-qscale:v", "7")
      .setVideoCodec("libvorbis")
      .addExtraArgs("-qscale:v", "5")
    .done();
```

**Comment by yeahbutwalter** [comment]
Thank you for that, worked out as expected. Great wrapper! The docs leave us wanting, hence my question. Thank you for taking the time to answer my question.

**Comment by bramp** [comment]
I've added this example to here https://github.com/bramp/ffmpeg-cli-wrapper/wiki/Random-Examples

I'm happy to accept documentation, or any other patches to increase the usability of the project. I however, don't want this to be a guide on "how to use ffmpeg", since that would be redundant with the official ffmpeg docs.
