### ISSUE TITLE
FFProbe constructor discrepancy

### ISSUE THREAD

**Issue by GenghisChen** [bramp/ffmpeg-cli-wrapper#74]
The FFProbe example on the main readme contains the following initialization:
`FFprobe ffprobe = new FFprobe("/path/to/ffprobe");`

Unfortunately, that constructor (which only takes a path) was removed in version 0.6
Chen

**Comment by bramp** [comment]
Thanks for reporting. I've built version 0.6.1 which fixes this problem, and should be on maven central shortly.

**Comment by GenghisChen** [comment]
Great, thanks!
