### ISSUE TITLE
Actual command string

### ISSUE THREAD

**Issue by yeahbutwalter** [bramp/ffmpeg-cli-wrapper#76]
Is there a way to get the actual string being executed? Would be extremely useful for debugging.

**Comment by bramp** [comment]
First off, how are you executing the command? This library provides a few different ways.

You may call the FFmpegBuilder.build() to get a List<String> of the arguments, for example:
```java
List<String> args = new FFmpegBuilder()
  .setInput("input.mp4")
  .addOutput("output.mp4")
  .build()
```

If you call
```java
FFmpeg ffmpeg = new FFmpeg("/path/to/ffmpeg");
ffmpeg.run(builder)
```
then that basically calls `.build()`, and prepends the path to ffmpeg. It may change the arguments slightly if you are using the SinglePassFFmpegJob or TwoPassFFmpegJob.

You could also hook into FFmpeg, for example:
```java
ffmpeg = new FFmpeg("/path/to/ffmpeg", new ProcessFunction() {

  final ProcessFunction runner = new RunProcessFunction();

  @Override
  public Process run(List<String> args) throws IOException {
    System.out.println(args);
    return runner.run(args);
  }
});
```

I'm open to suggestions on a way to make this easier for your usecase.

**Comment by yeahbutwalter** [comment]
FFmpegBuilder.build() is protected. It would be neat to be able to do

    FFmpegBuilder builder = new FFmpegBuilder()
        .setInput(infile)             
        .addInput(sampleWatermarkImg)
        .overrideOutputFiles(true) 
        .addOutput(destFile)   
        .setVideoCodec(codec)     
        .addExtraArgs(extraArgs)  
        .setVideoFrameRate(24, 1)     
        .setVideoResolution( iwidth , newHeight) 
        .setComplexVideoFilter("overlay=main_w-overlay_w-10:main_h-overlay_h-10")
        .setStrict(FFmpegBuilder.Strict.EXPERIMENTAL) 
        .done();

      log.debug( "Running ffmpeg as " + builder.getExecString());

or similar. Just to see what exactly is being called for debugging.

**Comment by yeahbutwalter** [comment]
I have a situation where the same code works on a windows machine but not on Debian. The error I get is

    [NULL @ 0x3c0eca0] Unable to find a suitable output format for ''

Which is why I really would like to see the exact command being executed rather than a list of arguments.

**Comment by yeahbutwalter** [comment]
The culprit turns out to be 

    .addExtraArgs(extraArgs)

The args list is

    [/home/peter/ffmpeg-3.2-64bit-static/ffmpeg, -y, -v, error, -i, /opt/foo/sb_video/original/fdafc21385a841f3acb3fd7cd1912975.mp4, -i, /opt/foo/sb_images/sb_watermark_25.png, -strict, experimental, -vcodec, libx264, -s, 852x480, -r, 24/1, -filter_complex, overlay=main_w-overlay_w-10:main_h-overlay_h-10, , /opt/foo/sb_video/sample/fdafc21385a841f3acb3fd7cd1912975.mp4]

where the culprit is the empty argument. For some reason this works on windows but not on Debian. With a clear command string I could have spotted this in the logs rightaway.

Anyways, thanks again for a great lib!

**Comment by bramp** [comment]
`build()` being protected is a oversight and I will change that. 

I will also not allow empty extra args.

Finally, the reason it is return as a list of arguments is because that is how it is passed to the ffmpeg binary. For example if there is a single element in the array with spaces in the middle, when it is executed the process see it as if the full argument had quotes around it. 

However, I guess there is a subtle difference in how window and Linux parses a empty arguments. 

I'll keep this bug open while I address my first two points.

**Comment by bramp** [comment]
Ok, [build()](https://github.com/bramp/ffmpeg-cli-wrapper/blob/master/src/main/java/net/bramp/ffmpeg/builder/FFmpegBuilder.java#L233) is actually public, and has been for a while. I suspect you are using a older version, please update to the latest version (currently 0.6.1).

I've pushed be6fbe834fdefa1d807da1a47f8578647094b760 to check that at-least one argument is passed to addExtraArgs(...) and that the first argument is not a blank string.
