### ISSUE TITLE
FFMPEG Command witn -vsync vfr

### ISSUE THREAD

**Issue by parmarsanjay** [bramp/ffmpeg-cli-wrapper#79]
I was not able to model following command in FFMPEG CLI.

ffmpeg -i input.mp4 -vf "select=gt(scene\,0.5)" -frames:v 5 -vsync vfr  out%02d.png

It kept throwing error for the "-vsync vfr" options. I tried adding that in video filter as well as addExtraArgs.

**Comment by bramp** [comment]
Please provide an example of the java you were using.

But quick question, did you do `.addExtraArgs("-vsync vfr")` ? or .addExtraArgs("-vsync", "vfr") ? The former most likely won't work, because java sends the 2 words to ffmpeg as one argument with a space in the middle.

**Comment by parmarsanjay** [comment]
Opps. Sorry my bad. I was doing the .addExtraArgs("-vsync vfr"). This verison worked. .addExtraArgs("-vsync", "vfr").
