### ISSUE TITLE
Not being able to find a class definition for FFmpeg.

### ISSUE THREAD

**Issue by turbobrick** [bramp/ffmpeg-cli-wrapper#80]
While trying to test the library I've got this error...

> Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/MoreObjects
> 	at net.bramp.ffmpeg.FFmpeg.<clinit>(FFmpeg.java:34)
> 	at test_mixer.OggEncoder.oggEncoder(OggEncoder.java:28)
> 	at test_mixer.Main.recordAudio(Main.java:96)
> 	at test_mixer.Main.main(Main.java:29)
> Caused by: java.lang.ClassNotFoundException: com.google.common.base.MoreObjects
> 	at java.net.URLClassLoader.findClass(Unknown Source)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	... 4 more

The paths that I have are the following ones...
`				String ffmpegPath = "C:\\Users\\Test\\EclipseWorkspace\\test_mixer\\ffmpeg\\bin\\ffmpeg.exe";`
				`String ffprobePath = "C:\\Users\\Test\\EclipseWorkspace\\test_mixer\\ffmpeg\\bin\\ffprobe.exe";`

Error is thrown while trying to instantiate the FFmpeg class. (I suposse the same will happen with the FFprobe class).
`FFmpeg ffmpeg = new FFmpeg(ffmpegPath);`

**Comment by bramp** [comment]
See issues #70 (same issue as this).

Basically your project, or one of your dependencies is using a older version of Guava. Please ensure you are using at least version 18.0.
