### ISSUE TITLE
Specify flag '-preset' for x264 together with '-vpre'

### ISSUE THREAD

**Issue by mayras** [bramp/ffmpeg-cli-wrapper#84]
According to http://stackoverflow.com/questions/4856039/ffmpeg-h264-problem-file-for-preset-not-found-on-xp please specify flag '-preset' to be able use preset 'ultrafast' for x264, I see in code that only:

if (!Strings.isNullOrEmpty(video_preset)) {         
       args.add("-vpre", video_preset);       
}

**Comment by bramp** [comment]
Ah so "-preset" is only supported by some codecs, and in those situations you most likely only want to specify one of -vpre or -preset.
