### ISSUE TITLE
Edge case with start_pts

### ISSUE THREAD

**Issue by borismcfishtank** [bramp/ffmpeg-cli-wrapper#87]
I've found an issue with certain encoders that when the stream they are sending out will overflow an int for the start_pts. The json parser threw a number format exception as the value was 3883260966 in the case I initially found.

I forked this and changed start_pts in FFmpegStream.java to a double for my purposes,
```
    // Edge case found on encoder, changed from int to double
    public double start_pts;
    public double start_time;
```
not sure if you want me to submit a pull request or if you want to change it yourself if you feel it is an issue that may strike other users.

**Comment by bramp** [comment]
I'm sure others will hit this, so a pull request would be great. However, I think a long be better than a double?

**Comment by borismcfishtank** [comment]
Good point.  Commited new one with longs and requested a pull.

**Comment by borismcfishtank** [comment]
Fixed
