### ISSUE TITLE
release the project as jar file

### ISSUE THREAD

**Issue by proewer** [bramp/ffmpeg-cli-wrapper#89]
Hi,
it's be very nice if you can release your project as jar lib, cause i use not maven. Sorry i'm old school.

Best regards,
Paul

**Comment by bramp** [comment]
Feel free to download the JAR from a web based maven: https://mvnrepository.com/artifact/net.bramp.ffmpeg/ffmpeg/0.6.1 (click Download (JAR)).

Does this meet your needs?

**Comment by proewer** [comment]
Hi,
i mean a jar file which incluse all dependencies.
Best regards,
Paul

**Comment by bramp** [comment]
ah a "fat jar".  Do other projects do that? (If you have examples, that would help me find best practices). However, this doesn't sound like something I'd want to do, for a few reasons:

1) Extra work/support on me
2) A far jar would cause problems for people with some of the same dependencies. For example, if you already used Guava, trying to use my far jar, would cause your conflicts. These kinds of conflicts are resolved at compile time by Maven.

Happy to hear competing arguments.

**Comment by bramp** [comment]
Ok, not enough interest.

**Comment by ben221199** [comment]
https://jar-download.com/artifacts/net.bramp.ffmpeg/ffmpeg
