### ISSUE TITLE
Allow extra arguments to FFprobe

### ISSUE THREAD

**Issue by zhaakhi** [bramp/ffmpeg-cli-wrapper#93]
It would be useful to support arbitrary extra arguments to FFprobe. Specifically I'm trying to set the expected input format, or a format/protocol whitelist. Currently this means I must reimplement probe(), since it does not support extraArgs like FFMpeg does.

**Comment by bramp** [comment]
Sounds like a good addition. Feel free to submit a pull request. Otherwise I'll get to this at some point (in weeks/months)

**Comment by Euklios** [comment]
This has been added in #268
