### ISSUE TITLE
convert h264 stream to mp4 stream

### ISSUE THREAD

**Issue by zgy520** [bramp/ffmpeg-cli-wrapper#95]
this project can be used to convert raw h264 stream to mp4 stream? if can , can provide a demo? thanks!

**Comment by bramp** [comment]
Yes, this library can be used to do that.

https://github.com/bramp/ffmpeg-cli-wrapper#video-encoding provides an example with many of the options. Have you tried to adapt that for your specific needs?

**Comment by ghostidentity** [comment]
Hello,

I am also having trouble on converting h264 stream from IP camera into mp4 file. It return PAUSE failed: 455 Method Not Valid In This State , operation not permitted.

Full source code might help to run the test.

Thanks,
Mark

**Comment by Euklios** [comment]
@ghostidentity Sorry for the late reply, but based on your provided context, this is most likely a permission error with the IP camera system
