### ISSUE TITLE
Get generated command line from a FFmpegJob or FFmpegBuilder instance

### ISSUE THREAD

**Issue by nmpgaspar** [bramp/ffmpeg-cli-wrapper#97]
Hi.

It seems to me that it is not possible to retrieve the corresponding ffmpeg command line that is used under the hood through a FFmpegJob or FFmpegBuilder instance (or by any other means).

Am I missing something and it is possible somehow? If not, any plans to include such feature?

**Comment by bramp** [comment]
You can call [build](https://bramp.github.io/ffmpeg-cli-wrapper/net/bramp/ffmpeg/builder/FFmpegBuilder.html#build--) on the FFmpegBuilder and it returns a list of the command line args.

Or you can construct a FFmpeg object with your own [ProcessFunction](https://bramp.github.io/ffmpeg-cli-wrapper/net/bramp/ffmpeg/RunProcessFunction.html) and capture the args that way.

**Comment by nmpgaspar** [comment]
Awesome, thank you!
